"""Reader for SAGE `.sav` save games (Battle for Middle-earth), sibling to `sage_map`.

A save is a serialized engine snapshot: a 16-byte file header, a flat sequence of named,
self-delimiting chunks, and an `SG_EOF` token. `sage_save.save` parses that container
losslessly - every chunk payload stays opaque bytes, so a save round-trips even though the
deep per-object state inside `CHUNK_GameLogic` is not decoded. `sage_save.xfer` implements the
`Xfer` wire primitives and `sage_save.chunks` builds typed decoders on them: `CHUNK_GameState`
(the description/date/map header), `CHUNK_GameStateMap` (whose embedded `.map` extracts to a
plain on-disk map every `sage_map` tool runs on unchanged), `CHUNK_Campaign` (a campaign save's
current campaign/mission and its persistent-hero carry-over roster), and `CHUNK_GameLogic` down
to its object template table and per-object index - so `iter_objects` names every live object on
the map. Object bodies and the deeper per-player/script state stay opaque, except that
`sage_save.players` harvests the fatal upgrade/science names from `CHUNK_Players`.
`sage_save.xref` (Phase 3) resolves the harvested ini-names against a
`sage_ini` `Game`, reporting the danglers - "will this save still load under this mod tree".
`sage_save.export` renders a save to JSON and `sage_save.edit` (`apply_json`) writes edited
JSON attributes back onto a save (length-preserving edits only - see that module).

The layouts here were reversed against the GPL Generals/Zero Hour `XferSave` source and
confirmed against a real BFME2 skirmish save; see sav_format.md for the full format notes.
"""

from sage_save.chunks import (
    CHUNK_CODECS,
    SCRIPT_ENGINE_PLAYER_SLOTS,
    AttackPriorityInfo,
    Campaign,
    CampaignHero,
    ChunkCodec,
    GameClientState,
    GameLogicState,
    GameStateHeader,
    GameStateMap,
    LivingWorldLogicState,
    NamedReveal,
    ObjectPrefix,
    ObjectTypesList,
    PlayersState,
    PlayerUpgrade,
    SaveDrawable,
    SaveObject,
    SavePlayer,
    ScriptCounter,
    ScriptEngineState,
    ScriptFlag,
    SmallChunk,
    TacticalView,
    TeamFactory,
    ToppleDirection,
    decode_campaign,
    decode_game_client,
    decode_game_logic,
    decode_game_state,
    decode_game_state_map,
    decode_living_world_logic,
    decode_object_prefix,
    decode_players,
    decode_script_engine,
    decode_small_chunk,
    decode_tactical_view,
    decode_team_factory,
    drawable_modules,
    encode_campaign,
    encode_game_client,
    encode_game_logic,
    encode_game_state,
    encode_game_state_map,
    encode_living_world_logic,
    encode_players,
    encode_script_engine,
    encode_small_chunk,
    encode_tactical_view,
    encode_team_factory,
    extract_map,
    iter_objects,
    living_world_names,
    living_world_object_templates,
    object_modules,
    object_veterancy_level,
    set_object_position,
)
from sage_save.coverage import (
    ChunkCoverage,
    CoverageSummary,
    chunk_coverage,
    coverage_summary,
)
from sage_save.diagnose import (
    KNOWN_CHUNK_VERSIONS,
    Diagnostic,
    diagnose_save,
    format_diagnosis,
)
from sage_save.edit import apply_json, apply_json_text
from sage_save.export import save_to_dict, save_to_json
from sage_save.players import NameList, harvest_name_lists
from sage_save.reversing import (
    NestedBlock,
    first_difference,
    format_block_tree,
    format_divergence,
    nested_block_tree,
)
from sage_save.save import (
    Chunk,
    SaveFile,
    SaveHeader,
    parse_save,
    parse_save_from_path,
    write_save,
    write_save_to_path,
)
from sage_save.xfer import XferReader
from sage_save.xref import (
    Finding,
    Reference,
    check_references,
    check_save,
    format_findings,
    harvest_campaign_references,
    harvest_living_world_references,
    harvest_object_references,
    harvest_object_upgrade_references,
    harvest_player_references,
    harvest_references,
    harvest_script_engine_references,
)

__all__ = [
    "CHUNK_CODECS",
    "SCRIPT_ENGINE_PLAYER_SLOTS",
    "AttackPriorityInfo",
    "Campaign",
    "CampaignHero",
    "Chunk",
    "ChunkCodec",
    "ChunkCoverage",
    "CoverageSummary",
    "Diagnostic",
    "Finding",
    "KNOWN_CHUNK_VERSIONS",
    "GameClientState",
    "GameLogicState",
    "GameStateHeader",
    "GameStateMap",
    "LivingWorldLogicState",
    "NameList",
    "NamedReveal",
    "NestedBlock",
    "ObjectPrefix",
    "ObjectTypesList",
    "PlayerUpgrade",
    "PlayersState",
    "Reference",
    "SaveDrawable",
    "SaveFile",
    "SaveHeader",
    "SaveObject",
    "SavePlayer",
    "ScriptCounter",
    "ScriptEngineState",
    "ScriptFlag",
    "SmallChunk",
    "TacticalView",
    "TeamFactory",
    "ToppleDirection",
    "XferReader",
    "apply_json",
    "apply_json_text",
    "check_references",
    "check_save",
    "chunk_coverage",
    "coverage_summary",
    "diagnose_save",
    "format_diagnosis",
    "decode_campaign",
    "decode_game_client",
    "decode_game_logic",
    "decode_game_state",
    "decode_game_state_map",
    "decode_living_world_logic",
    "decode_object_prefix",
    "decode_players",
    "decode_script_engine",
    "decode_small_chunk",
    "decode_tactical_view",
    "decode_team_factory",
    "drawable_modules",
    "encode_campaign",
    "encode_game_client",
    "encode_game_logic",
    "encode_game_state",
    "encode_game_state_map",
    "encode_living_world_logic",
    "encode_players",
    "encode_script_engine",
    "encode_small_chunk",
    "encode_tactical_view",
    "encode_team_factory",
    "extract_map",
    "first_difference",
    "format_block_tree",
    "format_divergence",
    "format_findings",
    "harvest_campaign_references",
    "harvest_living_world_references",
    "harvest_name_lists",
    "harvest_object_references",
    "harvest_object_upgrade_references",
    "harvest_player_references",
    "harvest_references",
    "harvest_script_engine_references",
    "living_world_names",
    "living_world_object_templates",
    "nested_block_tree",
    "object_modules",
    "object_veterancy_level",
    "iter_objects",
    "parse_save",
    "parse_save_from_path",
    "save_to_dict",
    "save_to_json",
    "set_object_position",
    "write_save",
    "write_save_to_path",
]
