"""Lossless reader/writer for the SAGE engine's W3D model format (`.w3d`): meshes, materials,
skeletons (hierarchies), animations (uncompressed and compressed), HLOD level-of-detail data,
collision boxes, and dazzles. See `sage_w3d.w3d` and README.md for the on-disk chunk layout and
the architecture (ordered children, payload-computed sizes, the leaf self-check that keeps a
whole-file round trip byte-exact even for a chunk this package cannot fully model);
`sage-w3d` is the command-line front end (`sage_w3d.__main__`)."""

from sage_w3d.animation import Animation, AnimationBitChannel, AnimationChannel, AnimationHeader
from sage_w3d.binary import (
    FixedString,
    Int32ListChunk,
    NulString,
    RgbaListChunk,
    StringChunk,
    UInt32ListChunk,
    Vec2ListChunk,
    Vec3ListChunk,
)
from sage_w3d.chunks import Rgba, UnknownChunk, Version, W3DDiagnostic, W3DError, chunk_name
from sage_w3d.compressed_animation import (
    AdaptiveDeltaAnimationChannel,
    AdaptiveDeltaBlock,
    AdaptiveDeltaData,
    CompressedAnimation,
    CompressedAnimationHeader,
    MotionAdaptiveDeltaData,
    MotionChannel,
    MotionTimeCodedData,
    MotionTimeCodedDatum,
    TimeCodedAnimationChannel,
    TimeCodedBitChannel,
    TimeCodedBitDatum,
    TimeCodedDatum,
)
from sage_w3d.hierarchy import Hierarchy, HierarchyHeader, HierarchyPivot, Pivots
from sage_w3d.hlod import HLOD, HLODArrayHeader, HLODHeader, HLODSubObject, HLODSubObjectArray
from sage_w3d.mesh import (
    GEOMETRY_TYPE_CAMERA_ALIGNED,
    GEOMETRY_TYPE_CAMERA_ORIENTED,
    GEOMETRY_TYPE_CAST_SHADOW,
    GEOMETRY_TYPE_HIDDEN,
    GEOMETRY_TYPE_SKIN,
    GEOMETRY_TYPE_TWO_SIDED,
    AABBTree,
    AABBTreeHeader,
    AABBTreeNode,
    AABBTreeNodes,
    MaterialInfo,
    MaterialPass,
    Mesh,
    MeshHeader,
    PerFaceTexCoordIds,
    Prelit,
    Shader,
    ShaderMaterial,
    ShaderMaterialHeader,
    ShaderMaterialProperty,
    ShaderMaterials,
    Shaders,
    Texture,
    TextureInfo,
    Textures,
    TextureStage,
    Triangle,
    Triangles,
    VertexInfluence,
    VertexInfluences,
    VertexMaterial,
    VertexMaterialInfo,
    VertexMaterials,
)
from sage_w3d.objects import CollisionBox, Dazzle
from sage_w3d.w3d import (
    W3DChunk,
    W3DFile,
    parse_w3d,
    parse_w3d_from_path,
    write_w3d,
    write_w3d_to_path,
)

__all__ = [
    "AABBTree",
    "AABBTreeHeader",
    "AABBTreeNode",
    "AABBTreeNodes",
    "AdaptiveDeltaAnimationChannel",
    "AdaptiveDeltaBlock",
    "AdaptiveDeltaData",
    "Animation",
    "AnimationBitChannel",
    "AnimationChannel",
    "AnimationHeader",
    "CollisionBox",
    "CompressedAnimation",
    "CompressedAnimationHeader",
    "Dazzle",
    "FixedString",
    "GEOMETRY_TYPE_CAMERA_ALIGNED",
    "GEOMETRY_TYPE_CAMERA_ORIENTED",
    "GEOMETRY_TYPE_CAST_SHADOW",
    "GEOMETRY_TYPE_HIDDEN",
    "GEOMETRY_TYPE_SKIN",
    "GEOMETRY_TYPE_TWO_SIDED",
    "HLOD",
    "HLODArrayHeader",
    "HLODHeader",
    "HLODSubObject",
    "HLODSubObjectArray",
    "Hierarchy",
    "HierarchyHeader",
    "HierarchyPivot",
    "Int32ListChunk",
    "MaterialInfo",
    "MaterialPass",
    "Mesh",
    "MeshHeader",
    "MotionAdaptiveDeltaData",
    "MotionChannel",
    "MotionTimeCodedData",
    "MotionTimeCodedDatum",
    "NulString",
    "PerFaceTexCoordIds",
    "Pivots",
    "Prelit",
    "Rgba",
    "RgbaListChunk",
    "Shader",
    "ShaderMaterial",
    "ShaderMaterialHeader",
    "ShaderMaterialProperty",
    "ShaderMaterials",
    "Shaders",
    "StringChunk",
    "Texture",
    "TextureInfo",
    "TextureStage",
    "Textures",
    "TimeCodedAnimationChannel",
    "TimeCodedBitChannel",
    "TimeCodedBitDatum",
    "TimeCodedDatum",
    "Triangle",
    "Triangles",
    "UInt32ListChunk",
    "UnknownChunk",
    "Vec2ListChunk",
    "Vec3ListChunk",
    "Version",
    "VertexInfluence",
    "VertexInfluences",
    "VertexMaterial",
    "VertexMaterialInfo",
    "VertexMaterials",
    "W3DChunk",
    "W3DDiagnostic",
    "W3DError",
    "W3DFile",
    "chunk_name",
    "parse_w3d",
    "parse_w3d_from_path",
    "write_w3d",
    "write_w3d_to_path",
]
