"""W3D chunk-id registry and the small value types shared across every modeled chunk: the
raw-chunk fallback (`UnknownChunk`), the exception and diagnostic types, and the two structs
(`Rgba`, `Version`) that appear inside many different chunks rather than owning one of their
own.

A `.w3d` file is a flat sequence of chunks: uint32 LE `chunk_type`, uint32 LE `size_field` whose
low 31 bits are the payload length and whose top bit (`flagged`) is conventionally set when the
payload holds nested chunks - conventionally, because real exporters do not always set it
consistently for the same chunk type, so parsing here always dispatches on `chunk_type`, never
on that bit (see `sage_w3d.binary`)."""

from dataclasses import dataclass

__all__ = [
    "CHUNK_NAMES",
    "Rgba",
    "UnknownChunk",
    "Version",
    "W3D_CHUNK_AABBTREE",
    "W3D_CHUNK_AABBTREE_HEADER",
    "W3D_CHUNK_AABBTREE_NODES",
    "W3D_CHUNK_AABBTREE_POLYINDICES",
    "W3D_CHUNK_AGGREGATE",
    "W3D_CHUNK_ANIMATION",
    "W3D_CHUNK_ANIMATION_BIT_CHANNEL",
    "W3D_CHUNK_ANIMATION_CHANNEL",
    "W3D_CHUNK_ANIMATION_HEADER",
    "W3D_CHUNK_BITANGENTS",
    "W3D_CHUNK_BOX",
    "W3D_CHUNK_COLLECTION",
    "W3D_CHUNK_COMPRESSED_ANIMATION",
    "W3D_CHUNK_COMPRESSED_ANIMATION_CHANNEL",
    "W3D_CHUNK_COMPRESSED_ANIMATION_HEADER",
    "W3D_CHUNK_COMPRESSED_ANIMATION_MOTION_CHANNEL",
    "W3D_CHUNK_COMPRESSED_BIT_CHANNEL",
    "W3D_CHUNK_DAZZLE",
    "W3D_CHUNK_DAZZLE_NAME",
    "W3D_CHUNK_DAZZLE_TYPENAME",
    "W3D_CHUNK_DCG",
    "W3D_CHUNK_DEFORM",
    "W3D_CHUNK_EMITTER",
    "W3D_CHUNK_HIERARCHY",
    "W3D_CHUNK_HIERARCHY_HEADER",
    "W3D_CHUNK_HLOD",
    "W3D_CHUNK_HLOD_AGGREGATE_ARRAY",
    "W3D_CHUNK_HLOD_HEADER",
    "W3D_CHUNK_HLOD_LOD_ARRAY",
    "W3D_CHUNK_HLOD_PROXY_ARRAY",
    "W3D_CHUNK_HLOD_SUB_OBJECT",
    "W3D_CHUNK_HLOD_SUB_OBJECT_ARRAY_HEADER",
    "W3D_CHUNK_HMODEL",
    "W3D_CHUNK_LIGHT",
    "W3D_CHUNK_LIGHTSCAPE",
    "W3D_CHUNK_LODMODEL",
    "W3D_CHUNK_MATERIAL_INFO",
    "W3D_CHUNK_MATERIAL_PASS",
    "W3D_CHUNK_MESH",
    "W3D_CHUNK_MESH_HEADER",
    "W3D_CHUNK_MESH_USER_TEXT",
    "W3D_CHUNK_MORPH_ANIMATION",
    "W3D_CHUNK_NORMALS_2",
    "W3D_CHUNK_NULL_OBJECT",
    "W3D_CHUNK_PER_FACE_TEXCOORD_IDS",
    "W3D_CHUNK_PIVOTS",
    "W3D_CHUNK_PIVOT_FIXUPS",
    "W3D_CHUNK_POINTS",
    "W3D_CHUNK_PRELIT_LIGHTMAP_MULTI_PASS",
    "W3D_CHUNK_PRELIT_LIGHTMAP_MULTI_TEXTURE",
    "W3D_CHUNK_PRELIT_UNLIT",
    "W3D_CHUNK_PRELIT_VERTEX",
    "W3D_CHUNK_PS2_SHADERS",
    "W3D_CHUNK_SCG",
    "W3D_CHUNK_SHADERS",
    "W3D_CHUNK_SHADER_IDS",
    "W3D_CHUNK_SHADER_MATERIAL",
    "W3D_CHUNK_SHADER_MATERIALS",
    "W3D_CHUNK_SHADER_MATERIAL_HEADER",
    "W3D_CHUNK_SHADER_MATERIAL_ID",
    "W3D_CHUNK_SHADER_MATERIAL_PROPERTY",
    "W3D_CHUNK_SOUNDROBJ",
    "W3D_CHUNK_STAGE_TEXCOORDS",
    "W3D_CHUNK_TANGENTS",
    "W3D_CHUNK_TEXTURE",
    "W3D_CHUNK_TEXTURES",
    "W3D_CHUNK_TEXTURE_IDS",
    "W3D_CHUNK_TEXTURE_INFO",
    "W3D_CHUNK_TEXTURE_NAME",
    "W3D_CHUNK_TEXTURE_STAGE",
    "W3D_CHUNK_TRIANGLES",
    "W3D_CHUNK_VERTEX_INFLUENCES",
    "W3D_CHUNK_VERTEX_MAPPER_ARGS0",
    "W3D_CHUNK_VERTEX_MAPPER_ARGS1",
    "W3D_CHUNK_VERTEX_MATERIAL",
    "W3D_CHUNK_VERTEX_MATERIALS",
    "W3D_CHUNK_VERTEX_MATERIAL_IDS",
    "W3D_CHUNK_VERTEX_MATERIAL_INFO",
    "W3D_CHUNK_VERTEX_MATERIAL_NAME",
    "W3D_CHUNK_VERTEX_NORMALS",
    "W3D_CHUNK_VERTEX_SHADE_INDICES",
    "W3D_CHUNK_VERTICES",
    "W3D_CHUNK_VERTICES_2",
    "W3DDiagnostic",
    "W3DError",
    "chunk_name",
]

W3D_CHUNK_MESH = 0x00000000
W3D_CHUNK_VERTICES = 0x00000002
W3D_CHUNK_VERTEX_NORMALS = 0x00000003
W3D_CHUNK_MESH_USER_TEXT = 0x0000000C
W3D_CHUNK_VERTEX_INFLUENCES = 0x0000000E
W3D_CHUNK_MESH_HEADER = 0x0000001F
W3D_CHUNK_TRIANGLES = 0x00000020
W3D_CHUNK_VERTEX_SHADE_INDICES = 0x00000022
W3D_CHUNK_PRELIT_UNLIT = 0x00000023
W3D_CHUNK_PRELIT_VERTEX = 0x00000024
W3D_CHUNK_PRELIT_LIGHTMAP_MULTI_PASS = 0x00000025
W3D_CHUNK_PRELIT_LIGHTMAP_MULTI_TEXTURE = 0x00000026
W3D_CHUNK_MATERIAL_INFO = 0x00000028
W3D_CHUNK_SHADERS = 0x00000029
W3D_CHUNK_VERTEX_MATERIALS = 0x0000002A
W3D_CHUNK_VERTEX_MATERIAL = 0x0000002B
W3D_CHUNK_VERTEX_MATERIAL_NAME = 0x0000002C
W3D_CHUNK_VERTEX_MATERIAL_INFO = 0x0000002D
W3D_CHUNK_VERTEX_MAPPER_ARGS0 = 0x0000002E
W3D_CHUNK_VERTEX_MAPPER_ARGS1 = 0x0000002F
W3D_CHUNK_TEXTURES = 0x00000030
W3D_CHUNK_TEXTURE = 0x00000031
W3D_CHUNK_TEXTURE_NAME = 0x00000032
W3D_CHUNK_TEXTURE_INFO = 0x00000033
W3D_CHUNK_MATERIAL_PASS = 0x00000038
W3D_CHUNK_VERTEX_MATERIAL_IDS = 0x00000039
W3D_CHUNK_SHADER_IDS = 0x0000003A
W3D_CHUNK_DCG = 0x0000003B
W3D_CHUNK_DIG = 0x0000003C
W3D_CHUNK_SCG = 0x0000003E
W3D_CHUNK_SHADER_MATERIAL_ID = 0x0000003F
W3D_CHUNK_TEXTURE_STAGE = 0x00000048
W3D_CHUNK_TEXTURE_IDS = 0x00000049
W3D_CHUNK_STAGE_TEXCOORDS = 0x0000004A
W3D_CHUNK_PER_FACE_TEXCOORD_IDS = 0x0000004B
W3D_CHUNK_SHADER_MATERIALS = 0x00000050
W3D_CHUNK_SHADER_MATERIAL = 0x00000051
W3D_CHUNK_SHADER_MATERIAL_HEADER = 0x00000052
W3D_CHUNK_SHADER_MATERIAL_PROPERTY = 0x00000053
W3D_CHUNK_DEFORM = 0x00000058
W3D_CHUNK_TANGENTS = 0x00000060
W3D_CHUNK_BITANGENTS = 0x00000061
W3D_CHUNK_PS2_SHADERS = 0x00000080
W3D_CHUNK_AABBTREE = 0x00000090
W3D_CHUNK_AABBTREE_HEADER = 0x00000091
W3D_CHUNK_AABBTREE_POLYINDICES = 0x00000092
W3D_CHUNK_AABBTREE_NODES = 0x00000093
W3D_CHUNK_VERTICES_2 = 0x00000C00
W3D_CHUNK_NORMALS_2 = 0x00000C01

W3D_CHUNK_HIERARCHY = 0x00000100
W3D_CHUNK_HIERARCHY_HEADER = 0x00000101
W3D_CHUNK_PIVOTS = 0x00000102
W3D_CHUNK_PIVOT_FIXUPS = 0x00000103

W3D_CHUNK_ANIMATION = 0x00000200
W3D_CHUNK_ANIMATION_HEADER = 0x00000201
W3D_CHUNK_ANIMATION_CHANNEL = 0x00000202
W3D_CHUNK_ANIMATION_BIT_CHANNEL = 0x00000203

W3D_CHUNK_COMPRESSED_ANIMATION = 0x00000280
W3D_CHUNK_COMPRESSED_ANIMATION_HEADER = 0x00000281
W3D_CHUNK_COMPRESSED_ANIMATION_CHANNEL = 0x00000282
W3D_CHUNK_COMPRESSED_BIT_CHANNEL = 0x00000283
W3D_CHUNK_COMPRESSED_ANIMATION_MOTION_CHANNEL = 0x00000284

W3D_CHUNK_MORPH_ANIMATION = 0x000002C0
W3D_CHUNK_HMODEL = 0x00000300
W3D_CHUNK_LODMODEL = 0x00000400
W3D_CHUNK_COLLECTION = 0x00000420
W3D_CHUNK_POINTS = 0x00000440
W3D_CHUNK_LIGHT = 0x00000460
W3D_CHUNK_EMITTER = 0x00000500
W3D_CHUNK_AGGREGATE = 0x00000600

W3D_CHUNK_HLOD = 0x00000700
W3D_CHUNK_HLOD_HEADER = 0x00000701
W3D_CHUNK_HLOD_LOD_ARRAY = 0x00000702
W3D_CHUNK_HLOD_SUB_OBJECT_ARRAY_HEADER = 0x00000703
W3D_CHUNK_HLOD_SUB_OBJECT = 0x00000704
W3D_CHUNK_HLOD_AGGREGATE_ARRAY = 0x00000705
W3D_CHUNK_HLOD_PROXY_ARRAY = 0x00000706

W3D_CHUNK_BOX = 0x00000740
W3D_CHUNK_NULL_OBJECT = 0x00000750
W3D_CHUNK_LIGHTSCAPE = 0x00000800

W3D_CHUNK_DAZZLE = 0x00000900
W3D_CHUNK_DAZZLE_NAME = 0x00000901
W3D_CHUNK_DAZZLE_TYPENAME = 0x00000902

W3D_CHUNK_SOUNDROBJ = 0x00000A00

# Names cover both the chunks this package models and the ones it deliberately keeps raw (see
# the module docstrings of w3d.py / mesh.py for which is which) - `chunk_name` and the CLI need
# a label for every id either way.
CHUNK_NAMES: dict[int, str] = {
    W3D_CHUNK_MESH: "MESH",
    W3D_CHUNK_VERTICES: "VERTICES",
    W3D_CHUNK_VERTEX_NORMALS: "VERTEX_NORMALS",
    W3D_CHUNK_MESH_USER_TEXT: "MESH_USER_TEXT",
    W3D_CHUNK_VERTEX_INFLUENCES: "VERTEX_INFLUENCES",
    W3D_CHUNK_MESH_HEADER: "MESH_HEADER",
    W3D_CHUNK_TRIANGLES: "TRIANGLES",
    W3D_CHUNK_VERTEX_SHADE_INDICES: "VERTEX_SHADE_INDICES",
    W3D_CHUNK_PRELIT_UNLIT: "PRELIT_UNLIT",
    W3D_CHUNK_PRELIT_VERTEX: "PRELIT_VERTEX",
    W3D_CHUNK_PRELIT_LIGHTMAP_MULTI_PASS: "PRELIT_LIGHTMAP_MULTI_PASS",
    W3D_CHUNK_PRELIT_LIGHTMAP_MULTI_TEXTURE: "PRELIT_LIGHTMAP_MULTI_TEXTURE",
    W3D_CHUNK_MATERIAL_INFO: "MATERIAL_INFO",
    W3D_CHUNK_SHADERS: "SHADERS",
    W3D_CHUNK_VERTEX_MATERIALS: "VERTEX_MATERIALS",
    W3D_CHUNK_VERTEX_MATERIAL: "VERTEX_MATERIAL",
    W3D_CHUNK_VERTEX_MATERIAL_NAME: "VERTEX_MATERIAL_NAME",
    W3D_CHUNK_VERTEX_MATERIAL_INFO: "VERTEX_MATERIAL_INFO",
    W3D_CHUNK_VERTEX_MAPPER_ARGS0: "VERTEX_MAPPER_ARGS0",
    W3D_CHUNK_VERTEX_MAPPER_ARGS1: "VERTEX_MAPPER_ARGS1",
    W3D_CHUNK_TEXTURES: "TEXTURES",
    W3D_CHUNK_TEXTURE: "TEXTURE",
    W3D_CHUNK_TEXTURE_NAME: "TEXTURE_NAME",
    W3D_CHUNK_TEXTURE_INFO: "TEXTURE_INFO",
    W3D_CHUNK_MATERIAL_PASS: "MATERIAL_PASS",
    W3D_CHUNK_VERTEX_MATERIAL_IDS: "VERTEX_MATERIAL_IDS",
    W3D_CHUNK_SHADER_IDS: "SHADER_IDS",
    W3D_CHUNK_DCG: "DCG",
    W3D_CHUNK_DIG: "DIG",
    W3D_CHUNK_SCG: "SCG",
    W3D_CHUNK_SHADER_MATERIAL_ID: "SHADER_MATERIAL_ID",
    W3D_CHUNK_TEXTURE_STAGE: "TEXTURE_STAGE",
    W3D_CHUNK_TEXTURE_IDS: "TEXTURE_IDS",
    W3D_CHUNK_STAGE_TEXCOORDS: "STAGE_TEXCOORDS",
    W3D_CHUNK_PER_FACE_TEXCOORD_IDS: "PER_FACE_TEXCOORD_IDS",
    W3D_CHUNK_SHADER_MATERIALS: "SHADER_MATERIALS",
    W3D_CHUNK_SHADER_MATERIAL: "SHADER_MATERIAL",
    W3D_CHUNK_SHADER_MATERIAL_HEADER: "SHADER_MATERIAL_HEADER",
    W3D_CHUNK_SHADER_MATERIAL_PROPERTY: "SHADER_MATERIAL_PROPERTY",
    W3D_CHUNK_DEFORM: "DEFORM",
    W3D_CHUNK_TANGENTS: "TANGENTS",
    W3D_CHUNK_BITANGENTS: "BITANGENTS",
    W3D_CHUNK_PS2_SHADERS: "PS2_SHADERS",
    W3D_CHUNK_AABBTREE: "AABBTREE",
    W3D_CHUNK_AABBTREE_HEADER: "AABBTREE_HEADER",
    W3D_CHUNK_AABBTREE_POLYINDICES: "AABBTREE_POLYINDICES",
    W3D_CHUNK_AABBTREE_NODES: "AABBTREE_NODES",
    W3D_CHUNK_VERTICES_2: "VERTICES_2",
    W3D_CHUNK_NORMALS_2: "NORMALS_2",
    W3D_CHUNK_HIERARCHY: "HIERARCHY",
    W3D_CHUNK_HIERARCHY_HEADER: "HIERARCHY_HEADER",
    W3D_CHUNK_PIVOTS: "PIVOTS",
    W3D_CHUNK_PIVOT_FIXUPS: "PIVOT_FIXUPS",
    W3D_CHUNK_ANIMATION: "ANIMATION",
    W3D_CHUNK_ANIMATION_HEADER: "ANIMATION_HEADER",
    W3D_CHUNK_ANIMATION_CHANNEL: "ANIMATION_CHANNEL",
    W3D_CHUNK_ANIMATION_BIT_CHANNEL: "ANIMATION_BIT_CHANNEL",
    W3D_CHUNK_COMPRESSED_ANIMATION: "COMPRESSED_ANIMATION",
    W3D_CHUNK_COMPRESSED_ANIMATION_HEADER: "COMPRESSED_ANIMATION_HEADER",
    W3D_CHUNK_COMPRESSED_ANIMATION_CHANNEL: "COMPRESSED_ANIMATION_CHANNEL",
    W3D_CHUNK_COMPRESSED_BIT_CHANNEL: "COMPRESSED_BIT_CHANNEL",
    W3D_CHUNK_COMPRESSED_ANIMATION_MOTION_CHANNEL: "COMPRESSED_ANIMATION_MOTION_CHANNEL",
    W3D_CHUNK_MORPH_ANIMATION: "MORPH_ANIMATION",
    W3D_CHUNK_HMODEL: "HMODEL",
    W3D_CHUNK_LODMODEL: "LODMODEL",
    W3D_CHUNK_COLLECTION: "COLLECTION",
    W3D_CHUNK_POINTS: "POINTS",
    W3D_CHUNK_LIGHT: "LIGHT",
    W3D_CHUNK_EMITTER: "EMITTER",
    W3D_CHUNK_AGGREGATE: "AGGREGATE",
    W3D_CHUNK_HLOD: "HLOD",
    W3D_CHUNK_HLOD_HEADER: "HLOD_HEADER",
    W3D_CHUNK_HLOD_LOD_ARRAY: "HLOD_LOD_ARRAY",
    W3D_CHUNK_HLOD_SUB_OBJECT_ARRAY_HEADER: "HLOD_SUB_OBJECT_ARRAY_HEADER",
    W3D_CHUNK_HLOD_SUB_OBJECT: "HLOD_SUB_OBJECT",
    W3D_CHUNK_HLOD_AGGREGATE_ARRAY: "HLOD_AGGREGATE_ARRAY",
    W3D_CHUNK_HLOD_PROXY_ARRAY: "HLOD_PROXY_ARRAY",
    W3D_CHUNK_BOX: "BOX",
    W3D_CHUNK_NULL_OBJECT: "NULL_OBJECT",
    W3D_CHUNK_LIGHTSCAPE: "LIGHTSCAPE",
    W3D_CHUNK_DAZZLE: "DAZZLE",
    W3D_CHUNK_DAZZLE_NAME: "DAZZLE_NAME",
    W3D_CHUNK_DAZZLE_TYPENAME: "DAZZLE_TYPENAME",
    W3D_CHUNK_SOUNDROBJ: "SOUNDROBJ",
}


def chunk_name(chunk_type: int) -> str:
    """The chunk's registry name, or `UNKNOWN_0x<hex>` for an id this package has never seen."""
    name = CHUNK_NAMES.get(chunk_type)
    if name is not None:
        return name
    return f"UNKNOWN_0x{chunk_type:08X}"


class W3DError(Exception):
    """Raised only when the input is not a chunk stream at all: 1 to 7 bytes (too short to hold
    even one chunk header - zero bytes is instead a valid, empty chunk stream), or a first chunk
    header whose declared payload size overruns the file. Anything recoverable - a malformed
    chunk further in, an unmodeled or unrecognized chunk id - is a diagnostic instead, never an
    exception."""


@dataclass
class W3DDiagnostic:
    """One recoverable parsing note: a chunk that didn't match its typed model, was truncated,
    or overran its container, and was kept as raw bytes instead. `chunk_type` is `None` for a
    file-level diagnostic (trailing bytes after the last top-level chunk)."""

    offset: int
    chunk_type: int | None
    message: str


@dataclass
class UnknownChunk:
    """A chunk kept as raw bytes: an id this package has no field model for, or one whose typed
    model didn't reproduce its payload exactly (see `sage_w3d.binary.parse_leaf` and
    `parse_container`). `data` is the exact payload - writing it back reproduces the chunk
    byte-for-byte regardless of why it ended up here."""

    chunk_type: int
    flagged: bool
    data: bytes


@dataclass(frozen=True)
class Version:
    """A chunk version number: on disk a single uint32, `major` in the high 16 bits and `minor`
    in the low 16."""

    major: int
    minor: int

    @staticmethod
    def parse(raw: int) -> "Version":
        return Version(major=raw >> 16, minor=raw & 0xFFFF)

    def encode(self) -> int:
        return ((self.major & 0xFFFF) << 16) | (self.minor & 0xFFFF)


@dataclass
class Rgba:
    """A 4-byte color/alpha quad. Stored as the raw 0-255 ints a chunk holds on disk - never as
    floats - so a value outside the "normal" color range still round-trips exactly."""

    r: int
    g: int
    b: int
    a: int
