"""Binary patches for the ROTWK SAGE engine (`game.dat` build `2.01.2614.37001`).

`apply_patches(game_dat, [patches...], output)` applies an ordered list of `Patch` instances to a
copy of the binary and writes the result:

    from sage_patch import AiReviveGatePatch, CommandSetLimitPatch, apply_patches
    apply_patches(
        "game.dat.backup",
        [CommandSetLimitPatch(count=64), AiReviveGatePatch()],
        output="game.dat",
    )

Each patch describes itself (`Patch.description`), its module docstring says how it works, and
`docs/<patch>.md` holds the reverse engineering. Some exported patches are experimental: check
`Patch.experimental`; `apply_patches` logs a warning for each one.
"""

from sage_patch.patcher import EXPERIMENTAL_WARNING, Patch, apply_patches
from sage_patch.patches import (
    AiReviveGatePatch,
    AutoDepositInflationPatch,
    BannerFilterPatch,
    CahFactionsPatch,
    CommandPointCostPatch,
    CommandPointUpkeepPatch,
    CommandSetLimitPatch,
    FireAtAttackerPatch,
    FoundationRebindPatch,
    HeadlessPatch,
    HealingReceivedPatch,
    HeroBarSlotsPatch,
    HeroManaPatch,
    HideModifierFxPatch,
    HordeOrphanTargetPatch,
    InflationReadoutPatch,
    LargeGroupBonusPatch,
    LifetimeFieldsPatch,
    MaintenanceCostPatch,
    MapListSymbolsPatch,
    MountHealthRatioPatch,
    MountSwapEjectPatch,
    MultiExecuteGatePatch,
    MultiSelectGroupPatch,
    PlayerHealFilterPatch,
    ProductionConditionPatch,
    ProductionSplitPatch,
    QueueIgnoreCpPatch,
    RadarStructureDiscsPatch,
    ReplayOutcomePatch,
    SciencePrereqPatch,
    SecondResourcePatch,
    ShareExperienceAllPatch,
    SkirmishReplayPatch,
    SpawnUnionPatch,
    SpecialPowerMusicPatch,
    SpellStoreUpgradePatch,
    TerrainResourceExpPatch,
    TriggerRechargeListPatch,
    UniqueProductionIdPatch,
    UnitPlateOptionPatch,
    UpgradeAliasPatch,
    UpgradeDescriptionPatch,
    UpgradeGrantListsPatch,
    WotrBattleObserversPatch,
)
from sage_patch.sagepatch import generate

__all__ = [
    "EXPERIMENTAL_WARNING",
    "AiReviveGatePatch",
    "AutoDepositInflationPatch",
    "BannerFilterPatch",
    "CahFactionsPatch",
    "CommandPointCostPatch",
    "CommandPointUpkeepPatch",
    "CommandSetLimitPatch",
    "FireAtAttackerPatch",
    "FoundationRebindPatch",
    "HeadlessPatch",
    "HealingReceivedPatch",
    "HideModifierFxPatch",
    "HeroBarSlotsPatch",
    "HeroManaPatch",
    "SpecialPowerMusicPatch",
    "HordeOrphanTargetPatch",
    "InflationReadoutPatch",
    "LargeGroupBonusPatch",
    "LifetimeFieldsPatch",
    "MaintenanceCostPatch",
    "MapListSymbolsPatch",
    "MountHealthRatioPatch",
    "MountSwapEjectPatch",
    "MultiExecuteGatePatch",
    "MultiSelectGroupPatch",
    "Patch",
    "PlayerHealFilterPatch",
    "ProductionConditionPatch",
    "ProductionSplitPatch",
    "QueueIgnoreCpPatch",
    "RadarStructureDiscsPatch",
    "ReplayOutcomePatch",
    "SciencePrereqPatch",
    "SecondResourcePatch",
    "ShareExperienceAllPatch",
    "SkirmishReplayPatch",
    "SpellStoreUpgradePatch",
    "SpawnUnionPatch",
    "TerrainResourceExpPatch",
    "TriggerRechargeListPatch",
    "UniqueProductionIdPatch",
    "UnitPlateOptionPatch",
    "UpgradeDescriptionPatch",
    "UpgradeAliasPatch",
    "UpgradeGrantListsPatch",
    "WotrBattleObserversPatch",
    "apply_patches",
    "generate",
]
