"""The patch table in `sage_patch/README.md`, generated from the registry.

    python -m sage_patch.readme          # rewrite the table in place
    python -m sage_patch.readme --check  # exit 1 if the table is out of date

Each row comes from the patch class itself: `name`, `description`, `experimental`,
`runtime_verified`, and the write-ups its module docstring cites (`write_ups`).
"""

from __future__ import annotations

import argparse
import inspect
import re
import sys
from pathlib import Path

from sage_patch.patcher import Patch
from sage_patch.registry import PATCHES

__all__ = ["README", "patch_table", "sync", "write_ups"]

PACKAGE = Path(__file__).resolve().parent
README = PACKAGE / "README.md"
START = "<!-- patch-table:start (generated by `python -m sage_patch.readme`; do not edit) -->"
END = "<!-- patch-table:end -->"

# A `docs/<path>.md` reference in a patch module's docstring.
_DOC_REFERENCE = re.compile(r"docs/([A-Za-z0-9._/-]+\.md)")
# The prefix a description opens with when the patch targets another binary.
_TARGET = re.compile(r"^([A-Za-z0-9_.]+\.exe) \(not game\.dat\):\s*")


def write_ups(cls: type[Patch]) -> list[Path]:
    """The write-ups under `sage_patch/docs` that this patch's module cites, in citation
    order, skipping any that do not exist."""
    found: list[Path] = []
    doc = inspect.getdoc(sys.modules[cls.__module__]) or ""
    for name in _DOC_REFERENCE.findall(doc):
        path = PACKAGE / "docs" / name
        if path.exists() and path not in found:
            found.append(path)
    return found


def _target(cls: type[Patch]) -> tuple[str, str]:
    """`(binary, description)` with the binary prefix taken off the description."""
    match = _TARGET.match(cls.description)
    if not match:
        return "game.dat", cls.description
    return match.group(1), cls.description[match.end() :]


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def _rows(patches: list[type[Patch]]) -> list[str]:
    rows = ["| Patch | What it does | In game | Write-up |", "| --- | --- | --- | --- |"]
    for cls in patches:
        _, description = _target(cls)
        links = ", ".join(
            f"[{path.stem}]({path.relative_to(PACKAGE).as_posix()})" for path in write_ups(cls)
        )
        rows.append(f"| `{cls.name}` | {_cell(description)} | {cls.runtime_verified} | {links} |")
    return rows


def patch_table() -> str:
    """The generated table section: game.dat patches, other binaries, then experimental ones,
    each in registry order."""
    groups: dict[str, list[type[Patch]]] = {}
    for cls in PATCHES.values():
        binary, _ = _target(cls)
        key = "Experimental" if cls.experimental else binary
        groups.setdefault(key, []).append(cls)
    order = ["game.dat"] + sorted(k for k in groups if k not in ("game.dat", "Experimental"))
    lines = [START]
    for key in [*order, "Experimental"]:
        if key not in groups:
            continue
        title = key if key == "Experimental" else f"`{key}`"
        lines += ["", f"### {title}", "", *_rows(groups[key])]
    lines += ["", END]
    return "\n".join(lines)


def sync(path: Path = README, check: bool = False) -> bool:
    """Bring the table in `path` up to date. Returns whether it already was; with `check`, the
    file is never written."""
    text = path.read_text(encoding="utf-8")
    start, end = text.index(START), text.index(END) + len(END)
    updated = text[:start] + patch_table() + text[end:]
    if updated == text:
        return True
    if not check:
        path.write_text(updated, encoding="utf-8", newline="\n")
    return False


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m sage_patch.readme")
    parser.add_argument("--check", action="store_true", help="only report whether it is current")
    args = parser.parse_args(argv)
    current = sync(check=args.check)
    if args.check and not current:
        print(f"{README} is out of date: run python -m sage_patch.readme", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
