/* Generated by `python -m sage_accel.gen` from ziglang's mingw headers; do not edit. */
#ifndef SAGE_ACCEL_VTABLES_H
#define SAGE_ACCEL_VTABLES_H

/* IDirect3DDevice9, d3d9.h */
#define DEVICE_SLOTS 119
#define DEVICE_SLOT_RESET 16
#define DEVICE_SLOT_PRESENT 17
static const char *const device_slot_names[DEVICE_SLOTS] = {
    "QueryInterface",
    "AddRef",
    "Release",
    "TestCooperativeLevel",
    "GetAvailableTextureMem",
    "EvictManagedResources",
    "GetDirect3D",
    "GetDeviceCaps",
    "GetDisplayMode",
    "GetCreationParameters",
    "SetCursorProperties",
    "SetCursorPosition",
    "ShowCursor",
    "CreateAdditionalSwapChain",
    "GetSwapChain",
    "GetNumberOfSwapChains",
    "Reset",
    "Present",
    "GetBackBuffer",
    "GetRasterStatus",
    "SetDialogBoxMode",
    "SetGammaRamp",
    "GetGammaRamp",
    "CreateTexture",
    "CreateVolumeTexture",
    "CreateCubeTexture",
    "CreateVertexBuffer",
    "CreateIndexBuffer",
    "CreateRenderTarget",
    "CreateDepthStencilSurface",
    "UpdateSurface",
    "UpdateTexture",
    "GetRenderTargetData",
    "GetFrontBufferData",
    "StretchRect",
    "ColorFill",
    "CreateOffscreenPlainSurface",
    "SetRenderTarget",
    "GetRenderTarget",
    "SetDepthStencilSurface",
    "GetDepthStencilSurface",
    "BeginScene",
    "EndScene",
    "Clear",
    "SetTransform",
    "GetTransform",
    "MultiplyTransform",
    "SetViewport",
    "GetViewport",
    "SetMaterial",
    "GetMaterial",
    "SetLight",
    "GetLight",
    "LightEnable",
    "GetLightEnable",
    "SetClipPlane",
    "GetClipPlane",
    "SetRenderState",
    "GetRenderState",
    "CreateStateBlock",
    "BeginStateBlock",
    "EndStateBlock",
    "SetClipStatus",
    "GetClipStatus",
    "GetTexture",
    "SetTexture",
    "GetTextureStageState",
    "SetTextureStageState",
    "GetSamplerState",
    "SetSamplerState",
    "ValidateDevice",
    "SetPaletteEntries",
    "GetPaletteEntries",
    "SetCurrentTexturePalette",
    "GetCurrentTexturePalette",
    "SetScissorRect",
    "GetScissorRect",
    "SetSoftwareVertexProcessing",
    "GetSoftwareVertexProcessing",
    "SetNPatchMode",
    "GetNPatchMode",
    "DrawPrimitive",
    "DrawIndexedPrimitive",
    "DrawPrimitiveUP",
    "DrawIndexedPrimitiveUP",
    "ProcessVertices",
    "CreateVertexDeclaration",
    "SetVertexDeclaration",
    "GetVertexDeclaration",
    "SetFVF",
    "GetFVF",
    "CreateVertexShader",
    "SetVertexShader",
    "GetVertexShader",
    "SetVertexShaderConstantF",
    "GetVertexShaderConstantF",
    "SetVertexShaderConstantI",
    "GetVertexShaderConstantI",
    "SetVertexShaderConstantB",
    "GetVertexShaderConstantB",
    "SetStreamSource",
    "GetStreamSource",
    "SetStreamSourceFreq",
    "GetStreamSourceFreq",
    "SetIndices",
    "GetIndices",
    "CreatePixelShader",
    "SetPixelShader",
    "GetPixelShader",
    "SetPixelShaderConstantF",
    "GetPixelShaderConstantF",
    "SetPixelShaderConstantI",
    "GetPixelShaderConstantI",
    "SetPixelShaderConstantB",
    "GetPixelShaderConstantB",
    "DrawRectPatch",
    "DrawTriPatch",
    "DeletePatch",
    "CreateQuery",
};
/* What a render thread does with each method. */
enum { SLOT_DRAINS, SLOT_QUEUED, SLOT_DIRECT };
static const unsigned char device_slot_kind[DEVICE_SLOTS] = {
    SLOT_DRAINS, /* QueryInterface */
    SLOT_DIRECT, /* AddRef */
    SLOT_DRAINS, /* Release */
    SLOT_DIRECT, /* TestCooperativeLevel */
    SLOT_DRAINS, /* GetAvailableTextureMem */
    SLOT_QUEUED, /* EvictManagedResources */
    SLOT_DIRECT, /* GetDirect3D */
    SLOT_DIRECT, /* GetDeviceCaps */
    SLOT_DIRECT, /* GetDisplayMode */
    SLOT_DIRECT, /* GetCreationParameters */
    SLOT_DRAINS, /* SetCursorProperties */
    SLOT_DRAINS, /* SetCursorPosition */
    SLOT_DRAINS, /* ShowCursor */
    SLOT_DRAINS, /* CreateAdditionalSwapChain */
    SLOT_DIRECT, /* GetSwapChain */
    SLOT_DIRECT, /* GetNumberOfSwapChains */
    SLOT_QUEUED, /* Reset */
    SLOT_QUEUED, /* Present */
    SLOT_DIRECT, /* GetBackBuffer */
    SLOT_DIRECT, /* GetRasterStatus */
    SLOT_DRAINS, /* SetDialogBoxMode */
    SLOT_QUEUED, /* SetGammaRamp */
    SLOT_DRAINS, /* GetGammaRamp */
    SLOT_DIRECT, /* CreateTexture */
    SLOT_DIRECT, /* CreateVolumeTexture */
    SLOT_DIRECT, /* CreateCubeTexture */
    SLOT_DIRECT, /* CreateVertexBuffer */
    SLOT_DIRECT, /* CreateIndexBuffer */
    SLOT_DIRECT, /* CreateRenderTarget */
    SLOT_DIRECT, /* CreateDepthStencilSurface */
    SLOT_QUEUED, /* UpdateSurface */
    SLOT_QUEUED, /* UpdateTexture */
    SLOT_DRAINS, /* GetRenderTargetData */
    SLOT_DRAINS, /* GetFrontBufferData */
    SLOT_QUEUED, /* StretchRect */
    SLOT_QUEUED, /* ColorFill */
    SLOT_DIRECT, /* CreateOffscreenPlainSurface */
    SLOT_QUEUED, /* SetRenderTarget */
    SLOT_DRAINS, /* GetRenderTarget */
    SLOT_QUEUED, /* SetDepthStencilSurface */
    SLOT_DRAINS, /* GetDepthStencilSurface */
    SLOT_QUEUED, /* BeginScene */
    SLOT_QUEUED, /* EndScene */
    SLOT_QUEUED, /* Clear */
    SLOT_QUEUED, /* SetTransform */
    SLOT_DRAINS, /* GetTransform */
    SLOT_QUEUED, /* MultiplyTransform */
    SLOT_QUEUED, /* SetViewport */
    SLOT_DRAINS, /* GetViewport */
    SLOT_QUEUED, /* SetMaterial */
    SLOT_DRAINS, /* GetMaterial */
    SLOT_QUEUED, /* SetLight */
    SLOT_DRAINS, /* GetLight */
    SLOT_QUEUED, /* LightEnable */
    SLOT_DRAINS, /* GetLightEnable */
    SLOT_QUEUED, /* SetClipPlane */
    SLOT_DRAINS, /* GetClipPlane */
    SLOT_QUEUED, /* SetRenderState */
    SLOT_DRAINS, /* GetRenderState */
    SLOT_DRAINS, /* CreateStateBlock */
    SLOT_DRAINS, /* BeginStateBlock */
    SLOT_DRAINS, /* EndStateBlock */
    SLOT_QUEUED, /* SetClipStatus */
    SLOT_DRAINS, /* GetClipStatus */
    SLOT_DRAINS, /* GetTexture */
    SLOT_QUEUED, /* SetTexture */
    SLOT_DRAINS, /* GetTextureStageState */
    SLOT_QUEUED, /* SetTextureStageState */
    SLOT_DRAINS, /* GetSamplerState */
    SLOT_QUEUED, /* SetSamplerState */
    SLOT_DRAINS, /* ValidateDevice */
    SLOT_QUEUED, /* SetPaletteEntries */
    SLOT_DRAINS, /* GetPaletteEntries */
    SLOT_QUEUED, /* SetCurrentTexturePalette */
    SLOT_DRAINS, /* GetCurrentTexturePalette */
    SLOT_QUEUED, /* SetScissorRect */
    SLOT_DRAINS, /* GetScissorRect */
    SLOT_QUEUED, /* SetSoftwareVertexProcessing */
    SLOT_DRAINS, /* GetSoftwareVertexProcessing */
    SLOT_QUEUED, /* SetNPatchMode */
    SLOT_DRAINS, /* GetNPatchMode */
    SLOT_QUEUED, /* DrawPrimitive */
    SLOT_QUEUED, /* DrawIndexedPrimitive */
    SLOT_QUEUED, /* DrawPrimitiveUP */
    SLOT_QUEUED, /* DrawIndexedPrimitiveUP */
    SLOT_DRAINS, /* ProcessVertices */
    SLOT_DIRECT, /* CreateVertexDeclaration */
    SLOT_QUEUED, /* SetVertexDeclaration */
    SLOT_DRAINS, /* GetVertexDeclaration */
    SLOT_QUEUED, /* SetFVF */
    SLOT_DRAINS, /* GetFVF */
    SLOT_DIRECT, /* CreateVertexShader */
    SLOT_QUEUED, /* SetVertexShader */
    SLOT_DRAINS, /* GetVertexShader */
    SLOT_QUEUED, /* SetVertexShaderConstantF */
    SLOT_DRAINS, /* GetVertexShaderConstantF */
    SLOT_QUEUED, /* SetVertexShaderConstantI */
    SLOT_DRAINS, /* GetVertexShaderConstantI */
    SLOT_QUEUED, /* SetVertexShaderConstantB */
    SLOT_DRAINS, /* GetVertexShaderConstantB */
    SLOT_QUEUED, /* SetStreamSource */
    SLOT_DRAINS, /* GetStreamSource */
    SLOT_QUEUED, /* SetStreamSourceFreq */
    SLOT_DRAINS, /* GetStreamSourceFreq */
    SLOT_QUEUED, /* SetIndices */
    SLOT_DRAINS, /* GetIndices */
    SLOT_DIRECT, /* CreatePixelShader */
    SLOT_QUEUED, /* SetPixelShader */
    SLOT_DRAINS, /* GetPixelShader */
    SLOT_QUEUED, /* SetPixelShaderConstantF */
    SLOT_DRAINS, /* GetPixelShaderConstantF */
    SLOT_QUEUED, /* SetPixelShaderConstantI */
    SLOT_DRAINS, /* GetPixelShaderConstantI */
    SLOT_QUEUED, /* SetPixelShaderConstantB */
    SLOT_DRAINS, /* GetPixelShaderConstantB */
    SLOT_DRAINS, /* DrawRectPatch */
    SLOT_DRAINS, /* DrawTriPatch */
    SLOT_DRAINS, /* DeletePatch */
    SLOT_DIRECT, /* CreateQuery */
};

/* ID3DXEffect, d3dx9effect.h */
#define EFFECT_SLOTS 79
static const char *const effect_slot_names[EFFECT_SLOTS] = {
    "QueryInterface",
    "AddRef",
    "Release",
    "GetDesc",
    "GetParameterDesc",
    "GetTechniqueDesc",
    "GetPassDesc",
    "GetFunctionDesc",
    "GetParameter",
    "GetParameterByName",
    "GetParameterBySemantic",
    "GetParameterElement",
    "GetTechnique",
    "GetTechniqueByName",
    "GetPass",
    "GetPassByName",
    "GetFunction",
    "GetFunctionByName",
    "GetAnnotation",
    "GetAnnotationByName",
    "SetValue",
    "GetValue",
    "SetBool",
    "GetBool",
    "SetBoolArray",
    "GetBoolArray",
    "SetInt",
    "GetInt",
    "SetIntArray",
    "GetIntArray",
    "SetFloat",
    "GetFloat",
    "SetFloatArray",
    "GetFloatArray",
    "SetVector",
    "GetVector",
    "SetVectorArray",
    "GetVectorArray",
    "SetMatrix",
    "GetMatrix",
    "SetMatrixArray",
    "GetMatrixArray",
    "SetMatrixPointerArray",
    "GetMatrixPointerArray",
    "SetMatrixTranspose",
    "GetMatrixTranspose",
    "SetMatrixTransposeArray",
    "GetMatrixTransposeArray",
    "SetMatrixTransposePointerArray",
    "GetMatrixTransposePointerArray",
    "SetString",
    "GetString",
    "SetTexture",
    "GetTexture",
    "GetPixelShader",
    "GetVertexShader",
    "SetArrayRange",
    "GetPool",
    "SetTechnique",
    "GetCurrentTechnique",
    "ValidateTechnique",
    "FindNextValidTechnique",
    "IsParameterUsed",
    "Begin",
    "BeginPass",
    "CommitChanges",
    "EndPass",
    "End",
    "GetDevice",
    "OnLostDevice",
    "OnResetDevice",
    "SetStateManager",
    "GetStateManager",
    "BeginParameterBlock",
    "EndParameterBlock",
    "ApplyParameterBlock",
    "DeleteParameterBlock",
    "CloneEffect",
    "SetRawValue",
};

/* IDirect3DTexture9, d3d9.h */
#define TEXTURE_SLOTS 22
#define TEXTURE_SLOT_LOCK_RECT 19
static const char *const texture_slot_names[TEXTURE_SLOTS] = {
    "QueryInterface",
    "AddRef",
    "Release",
    "GetDevice",
    "SetPrivateData",
    "GetPrivateData",
    "FreePrivateData",
    "SetPriority",
    "GetPriority",
    "PreLoad",
    "GetType",
    "SetLOD",
    "GetLOD",
    "GetLevelCount",
    "SetAutoGenFilterType",
    "GetAutoGenFilterType",
    "GenerateMipSubLevels",
    "GetLevelDesc",
    "GetSurfaceLevel",
    "LockRect",
    "UnlockRect",
    "AddDirtyRect",
};

/* IDirect3DSurface9, d3d9.h */
#define SURFACE_SLOTS 17
#define SURFACE_SLOT_LOCK_RECT 13
static const char *const surface_slot_names[SURFACE_SLOTS] = {
    "QueryInterface",
    "AddRef",
    "Release",
    "GetDevice",
    "SetPrivateData",
    "GetPrivateData",
    "FreePrivateData",
    "SetPriority",
    "GetPriority",
    "PreLoad",
    "GetType",
    "GetContainer",
    "GetDesc",
    "LockRect",
    "UnlockRect",
    "GetDC",
    "ReleaseDC",
};

/* IDirect3DVertexBuffer9, d3d9.h */
#define VERTEX_BUFFER_SLOTS 14
#define VERTEX_BUFFER_SLOT_LOCK 11
static const char *const vertex_buffer_slot_names[VERTEX_BUFFER_SLOTS] = {
    "QueryInterface",
    "AddRef",
    "Release",
    "GetDevice",
    "SetPrivateData",
    "GetPrivateData",
    "FreePrivateData",
    "SetPriority",
    "GetPriority",
    "PreLoad",
    "GetType",
    "Lock",
    "Unlock",
    "GetDesc",
};

/* IDirect3DIndexBuffer9, d3d9.h */
#define INDEX_BUFFER_SLOTS 14
#define INDEX_BUFFER_SLOT_LOCK 11
static const char *const index_buffer_slot_names[INDEX_BUFFER_SLOTS] = {
    "QueryInterface",
    "AddRef",
    "Release",
    "GetDevice",
    "SetPrivateData",
    "GetPrivateData",
    "FreePrivateData",
    "SetPriority",
    "GetPriority",
    "PreLoad",
    "GetType",
    "Lock",
    "Unlock",
    "GetDesc",
};

/* IDirect3D9, d3d9.h */
#define DIRECT3D_SLOTS 17
#define DIRECT3D_SLOT_CREATE_DEVICE 16
static const char *const direct3d_slot_names[DIRECT3D_SLOTS] = {
    "QueryInterface",
    "AddRef",
    "Release",
    "RegisterSoftwareDevice",
    "GetAdapterCount",
    "GetAdapterIdentifier",
    "GetAdapterModeCount",
    "EnumAdapterModes",
    "GetAdapterDisplayMode",
    "CheckDeviceType",
    "CheckDeviceFormat",
    "CheckDeviceMultiSampleType",
    "CheckDepthStencilMatch",
    "CheckDeviceFormatConversion",
    "GetDeviceCaps",
    "GetAdapterMonitor",
    "CreateDevice",
};

#endif
