"""Generate `src/vtables.h`: slot names and dispositions for the interfaces the module hooks.

Run as `python -m sage_accel.gen` after changing anything here; the output is committed so the C
reads on its own. Method order comes from the mingw-w64 D3D headers that ship inside `ziglang`,
which is the same order as each interface's vtable.

The one fact not in a header is **what a render thread does with each device method**. `QUEUED`
and `DIRECT` are `bfme2_accel.dll`'s answer (`sage_patch/docs/accel-queue.md`): a queued method runs
later on the worker; a direct one runs at once on the calling thread without waiting; every other
method first waits for the worker to drain the queue. M1 counts calls under this split so that M2's
cost is known before M2 exists.
"""

from __future__ import annotations

import re
from pathlib import Path

__all__ = ["DIRECT", "HEADER", "INTERFACES", "QUEUED", "header_dir", "methods", "render"]

HEADER = Path(__file__).resolve().parent / "src" / "vtables.h"

#: `(C prefix, header, interface)` for every vtable M1 reads slot names from.
INTERFACES = (
    ("DEVICE", "d3d9.h", "IDirect3DDevice9"),
    ("EFFECT", "d3dx9effect.h", "ID3DXEffect"),
    ("TEXTURE", "d3d9.h", "IDirect3DTexture9"),
    ("SURFACE", "d3d9.h", "IDirect3DSurface9"),
    ("VERTEX_BUFFER", "d3d9.h", "IDirect3DVertexBuffer9"),
    ("INDEX_BUFFER", "d3d9.h", "IDirect3DIndexBuffer9"),
    ("DIRECT3D", "d3d9.h", "IDirect3D9"),
)

#: The 47 `IDirect3DDevice9` methods `bfme2_accel.dll` queues (read at its wrapper table
#: `0x1005BBF0`). Every other device method drains the queue first.
QUEUED = frozenset(
    {
        "EvictManagedResources", "Reset", "Present", "SetGammaRamp", "UpdateSurface",
        "UpdateTexture", "StretchRect", "ColorFill", "SetRenderTarget", "SetDepthStencilSurface",
        "BeginScene", "EndScene", "Clear", "SetTransform", "MultiplyTransform", "SetViewport",
        "SetMaterial", "SetLight", "LightEnable", "SetClipPlane", "SetRenderState",
        "SetClipStatus", "SetTexture", "SetTextureStageState", "SetSamplerState",
        "SetPaletteEntries", "SetCurrentTexturePalette", "SetScissorRect",
        "SetSoftwareVertexProcessing", "SetNPatchMode", "DrawPrimitive", "DrawIndexedPrimitive",
        "DrawPrimitiveUP", "DrawIndexedPrimitiveUP", "SetVertexDeclaration", "SetFVF",
        "SetVertexShader", "SetVertexShaderConstantF", "SetVertexShaderConstantI",
        "SetVertexShaderConstantB", "SetStreamSource", "SetStreamSourceFreq", "SetIndices",
        "SetPixelShader", "SetPixelShaderConstantF", "SetPixelShaderConstantI",
        "SetPixelShaderConstantB",
    }
)  # fmt: skip

#: The 22 device methods `bfme2_accel.dll` runs at once without draining the queue - its wrappers
#: for them call neither the enqueue (`0x1003E240`) nor the flush (`0x1003F350`). Every creation
#: method is here, and `AddRef`, but not `Release`: releasing the device drains.
DIRECT = frozenset(
    {
        "AddRef", "TestCooperativeLevel", "GetDirect3D", "GetDeviceCaps", "GetDisplayMode",
        "GetCreationParameters", "GetSwapChain", "GetNumberOfSwapChains", "GetBackBuffer",
        "GetRasterStatus", "CreateTexture", "CreateVolumeTexture", "CreateCubeTexture",
        "CreateVertexBuffer", "CreateIndexBuffer", "CreateRenderTarget",
        "CreateDepthStencilSurface", "CreateOffscreenPlainSurface", "CreateVertexDeclaration",
        "CreateVertexShader", "CreatePixelShader", "CreateQuery",
    }
)  # fmt: skip

_DECLARE = re.compile(r"DECLARE_INTERFACE_(?:IID_)?\((\w+)\s*,")
_METHOD = re.compile(r"STDMETHOD_?\((?:[^,()]+,\s*)?(\w+)\)")


def header_dir() -> Path:
    import ziglang  # noqa: PLC0415 - only the generator and the build need the toolchain

    return Path(ziglang.__file__).resolve().parent / "lib/libc/include/any-windows-any"


def methods(header: str, interface: str) -> list[str]:
    """`interface`'s methods in vtable order, `IUnknown`'s three first."""
    text = (header_dir() / header).read_text(encoding="utf-8", errors="replace")
    for match in _DECLARE.finditer(text):
        if match.group(1) == interface:
            body = text[match.end() : text.index("};", match.end())]
            return _METHOD.findall(body)
    raise LookupError(f"{interface} is not declared in {header}")


def render() -> str:
    out = [
        "/* Generated by `python -m sage_accel.gen` from ziglang's mingw headers; do not edit. */",
        "#ifndef SAGE_ACCEL_VTABLES_H",
        "#define SAGE_ACCEL_VTABLES_H",
        "",
    ]
    for prefix, header, interface in INTERFACES:
        names = methods(header, interface)
        out.append(f"/* {interface}, {header} */")
        out.append(f"#define {prefix}_SLOTS {len(names)}")
        for slot, name in enumerate(names):
            if name in {"CreateDevice", "Present", "Reset", "Lock", "LockRect"}:
                out.append(f"#define {prefix}_SLOT_{_upper(name)} {slot}")
        out.append(f"static const char *const {prefix.lower()}_slot_names[{prefix}_SLOTS] = {{")
        out.extend(f'    "{name}",' for name in names)
        out.append("};")
        if prefix == "DEVICE":
            unknown = (QUEUED | DIRECT) - set(names)
            if unknown:
                raise LookupError(f"QUEUED/DIRECT name no device method: {sorted(unknown)}")
            if QUEUED & DIRECT:
                raise LookupError(f"queued and direct at once: {sorted(QUEUED & DIRECT)}")
            out.append("/* What a render thread does with each method. */")
            out.append("enum { SLOT_DRAINS, SLOT_QUEUED, SLOT_DIRECT };")
            out.append("static const unsigned char device_slot_kind[DEVICE_SLOTS] = {")
            out.extend(f"    {_kind(name)}, /* {name} */" for name in names)
            out.append("};")
        out.append("")
    out.append("#endif")
    return "\n".join(out) + "\n"


def _kind(name: str) -> str:
    if name in QUEUED:
        return "SLOT_QUEUED"
    return "SLOT_DIRECT" if name in DIRECT else "SLOT_DRAINS"


def _upper(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).upper()


if __name__ == "__main__":
    HEADER.write_text(render(), encoding="utf-8", newline="\n")
    print(HEADER)
