"""Derive one skin per Edain faction from the faction's own emblem art.

Each faction's palette is sampled, not chosen. Two anchors come out of the emblem in
`sage_mods/edain/icons/` - the dark field it is drawn on, and the brightest accent drawn over
it - and every other token is a fixed function of those two, so no skin is hand-tuned past the
rule that produced it. The rules, in order, per faction:

  1. emblem     - the art has a chromatic field and a brighter accent: field sets the ground,
                  accent sets the trim.
  2. preferred  - the art is monochrome but Edain moved the faction off the stock team colour
                  in playertemplate.ini: that colour sets the trim. Only Isengard qualifies -
                  nearly every other faction still carries the stock `R:43 G:150 B:179`.
  3. monochrome - the art is monochrome and the mod says nothing. The emblem is the palette,
                  and the only judgement in the set is a faint hue bias on the neutral, noted
                  per faction below and on the gallery page.

Run it to write all four outputs, each of which is generated and none of which is hand-edited:

    build/theme-demo/assets/factions.css   the thirteen skins, for the demo pages
    build/theme-demo/faction-<slug>.html   one demo page per faction
    build/theme-demo/factions.html         the gallery, each palette beside its emblem
    sage_utils/webtheme.py                 the palettes the generated site actually uses

Re-running it moves every palette with the art: the emblems are the source of truth.
"""

from __future__ import annotations

import colorsys
import os
import re
import shutil

from PIL import Image

from sage_mods.edain.replay import FACTION_ICONS

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICONS = os.path.join(REPO, "sage_mods", "edain", "icons")
DEMO = os.path.join(REPO, "build", "theme-demo")
WEBTHEME = os.path.join(REPO, "sage_utils", "webtheme.py")
MARKER = "# --- generated by tools/build_faction_skins.py - do not edit below this line ---"
# `ruff format` would unpack the grouped palette layout `_skin_entry` writes, so the generated
# block is fenced off from it. A fence rather than an exclude in pyproject: the hand-written half
# of webtheme.py, above the marker, stays formatted like every other module in the tree.
FMT_OFF = "# fmt: off"
FMT_ON = "# fmt: on"

MONOCHROME_GONDOR = (
    "White tree on black. The bias is a faint silver-blue, the only judgement in the palette."
)
MONOCHROME_ARNOR = "Monochrome like Gondor, biased a step colder for the northern kingdom."
PREFERRED_ISENGARD = (
    "The art is monochrome, but Edain moved this faction off the stock team colour to a gold. "
    "That gold is the trim."
)

# name, slug, emblem file, the Edain side it belongs to, alignment, and the override that
# applies when the art alone says nothing. `bias` is a hue in turns for an otherwise grey
# emblem; `color` is a PreferredColor the mod set itself.
FACTIONS = [
    (
        "Gondor",
        "gondor",
        "Gondor_frontpage.webp",
        "Men",
        "Good",
        {"rule": "monochrome", "bias": 0.58, "note": MONOCHROME_GONDOR},
    ),
    (
        "Arnor",
        "arnor",
        "Arnor_frontpage.webp",
        "Men",
        "Good",
        {"rule": "monochrome", "bias": 0.60, "note": MONOCHROME_ARNOR},
    ),
    ("Belfalas", "belfalas", "Belfalas_frontpage.webp", "Men", "Good", {}),
    ("Rohan", "rohan", "Rohan_frontpage.webp", "Rohan", "Good", {}),
    ("Imladris", "imladris", "Imladris_frontpage.webp", "Imladris", "Good", {}),
    ("Lothl&oacute;rien", "lothlorien", "Lothlorien_frontpage.webp", "Elves", "Good", {}),
    ("Erebor", "erebor", "Erebor_frontpage.webp", "Dwarves", "Good", {}),
    ("Ered Luin", "eredluin", "Ered-Luin_frontpage.webp", "Dwarves", "Good", {}),
    ("Iron Hills", "ironhills", "Iron_Hills_frontpage.webp", "Dwarves", "Good", {}),
    (
        "Isengard",
        "isengard",
        "Isengard_frontpage.webp",
        "Isengard",
        "Evil",
        {"rule": "preferred", "color": (216, 175, 48), "note": PREFERRED_ISENGARD},
    ),
    ("Mordor", "mordor", "Mordor_frontpage.webp", "Mordor", "Evil", {}),
    ("Misty Mountains", "misty", "Misty_Mountains_frontpage.webp", "Wild", "Evil", {}),
    ("Angmar", "angmar", "Angmar_frontpage.webp", "Angmar", "Evil", {}),
]

# The chart series and the faction stripes are shared across every skin: they mean the same
# thing on every page, so they are not the faction's to recolour.
SHARED = """  --s1: #3987e5; --s2: #199e70; --s3: #c98500; --s4: #3f9e3f;
  --s5: #9085e9; --s6: #e66767; --s7: #d55181; --s8: #d95926;
  --f-gondor: #6f9dd0; --f-mordor: #c4543f; --f-imladris: #d9bd6a;
  --f-misty: #8fb069; --f-eredluin: #a89076;"""

# The designed default, unlike the thirteen: gunmetal ground, polished steel trim. A choice,
# not a sample, so it is written here rather than derived.
STEEL = {
    "plane": "#0d1219",
    "surface": "#161e28",
    "raise_": "#1e2835",
    "ink": "#dce5f0",
    "ink2": "#b0bfd0",
    "muted": "#8393a6",
    "hair": "#33445a",
    "hair2": "#263444",
    "trim": "#7ea9d6",
    "trimhi": "#cde3fb",
    "mark": "#e2705e",
    "link": "#58bcd8",
    "good": "#63bb95",
    "track": "#1a2430",
}

RULE_LABELS = {
    "emblem": "from the emblem",
    "preferred": "from playertemplate",
    "monochrome": "monochrome art",
}


def plain(name: str) -> str:
    """A display name with its HTML entities flattened, for alt text and comments."""
    return re.sub("&[a-z]+;", "o", name)


def hexof(hue: float, light: float, sat: float) -> str:
    red, green, blue = rgbof(hue, light, sat)
    return f"#{red:02x}{green:02x}{blue:02x}"


def rgbof(hue: float, light: float, sat: float) -> tuple[int, int, int]:
    red, green, blue = colorsys.hls_to_rgb(
        hue % 1.0, max(0.0, min(1.0, light)), max(0.0, min(1.0, sat))
    )
    return round(red * 255), round(green * 255), round(blue * 255)


def luminance(rgb: tuple[int, int, int]) -> float:
    channels = []
    for raw in rgb:
        value = raw / 255.0
        channels.append(value / 12.92 if value <= 0.04045 else ((value + 0.055) / 1.055) ** 2.4)
    return 0.2126 * channels[0] + 0.7152 * channels[1] + 0.0722 * channels[2]


def contrast(a: tuple[int, int, int], b: tuple[int, int, int]) -> float:
    lit, dim = sorted((luminance(a), luminance(b)), reverse=True)
    return (lit + 0.05) / (dim + 0.05)


def hue_gap(a: float, b: float) -> float:
    """The distance between two hues in turns, the short way round the wheel."""
    return min(abs(a - b), 1 - abs(a - b))


def sample(path: str) -> tuple[tuple | None, tuple | None, float]:
    """The emblem's `(field, accent, grey %)`, each anchor `(hue, lightness, saturation)`.

    Pixels are bucketed by hue and split by lightness: the dark half is the field the emblem
    is drawn on, the light half the accent drawn over it. An emblem with no chromatic pixels
    at all - three of them are pure greyscale - returns None for both anchors.
    """
    image = Image.open(path).convert("RGBA")
    field_buckets: dict[int, list[float]] = {}
    accent_buckets: dict[int, list[float]] = {}
    grey = 0
    total = 0
    for red, green, blue, alpha in image.get_flattened_data():
        if alpha < 200:
            continue
        total += 1
        hue, light, sat = colorsys.rgb_to_hls(red / 255.0, green / 255.0, blue / 255.0)
        if sat < 0.18 or light < 0.05 or light > 0.95:
            grey += 1
            continue
        target = field_buckets if light < 0.36 else accent_buckets
        entry = target.setdefault(int(hue * 36) % 36, [0.0, 0.0, 0.0, 0.0])
        entry[0] += 1
        entry[1] += hue
        entry[2] += light
        entry[3] += sat
    if not total:
        raise ValueError(f"no opaque pixels in {path}")

    def best(buckets: dict[int, list[float]], weight_by_sat: bool) -> tuple | None:
        """The dominant bucket: by area for the field, by area x saturation for the accent -
        an accent is what the eye picks out, which is chroma, not coverage."""
        if not buckets:
            return None
        _, (count, hues, lights, sats) = max(
            buckets.items(),
            key=lambda kv: kv[1][0] * (kv[1][3] / kv[1][0] if weight_by_sat else 1),
        )
        return (hues / count, lights / count, sats / count, 100.0 * count / total)

    return best(field_buckets, False), best(accent_buckets, True), 100.0 * grey / total


def tokens_for(field: tuple, accent: tuple) -> dict[str, str]:
    """The whole token set as a fixed function of the two anchors."""
    field_hue, field_sat = field[0], min(field[2], 0.45)
    accent_hue, accent_light, accent_sat = accent[0], accent[1], accent[2]
    trim_light = max(0.50, min(0.62, accent_light))
    trim_sat = max(0.42, min(0.74, accent_sat))
    high = rgbof(accent_hue, 0.80, max(0.38, min(0.68, accent_sat * 0.9)))

    # The diverging pair keeps its meaning on every skin - cool is above the line, warm is
    # below - but it cannot sit on top of the trim. Where the faction's own colour lands in
    # one of those two zones, that side of the pair rotates away from it.
    link_hue = 0.44 if hue_gap(accent_hue, 0.44) > 0.07 else 0.55
    mark_hue = 0.02 if hue_gap(accent_hue, 0.02) > 0.06 else 0.08
    mark_light = 0.58 if mark_hue == 0.02 else 0.62

    # The trim and the link both carry small text (card side-labels, the primary button, the
    # only inline links), so neither is allowed below 4.5:1 on the surface it sits on. A dark
    # faction accent gets lifted until it clears, keeping its hue.
    surface_rgb = rgbof(field_hue, 0.088, field_sat * 0.72)

    def lift(hue: float, light: float, sat: float) -> float:
        while light < 0.86 and contrast(rgbof(hue, light, sat), surface_rgb) < 4.5:
            light += 0.015
        return light

    trim_light = lift(accent_hue, trim_light, trim_sat)
    link_light = lift(link_hue, 0.54, 0.52)

    return {
        "plane": hexof(field_hue, 0.055, field_sat * 0.85),
        "surface": hexof(field_hue, 0.088, field_sat * 0.72),
        "raise_": hexof(field_hue, 0.128, field_sat * 0.66),
        "track": hexof(field_hue, 0.102, field_sat * 0.70),
        "hair": hexof(field_hue, 0.245, field_sat * 0.62),
        "hair2": hexof(field_hue, 0.172, field_sat * 0.58),
        "ink": hexof(field_hue, 0.900, 0.13),
        "ink2": hexof(field_hue, 0.755, 0.11),
        "muted": hexof(field_hue, 0.578, 0.10),
        "trim": hexof(accent_hue, trim_light, trim_sat),
        "trimhi": f"#{high[0]:02x}{high[1]:02x}{high[2]:02x}",
        "bevel": f"rgba({high[0]}, {high[1]}, {high[2]}, 0.12)",
        "mark": hexof(mark_hue, mark_light, 0.68),
        "link": hexof(link_hue, link_light, 0.52),
        "good": hexof(0.36, 0.56, 0.42),
    }


def build() -> list[dict]:
    """Every faction's row: its identity, the rule that applied, and its derived tokens."""
    rows = []
    for name, slug, icon, side, align, override in FACTIONS:
        field, accent, grey = sample(os.path.join(ICONS, icon))
        rule = override.get("rule", "emblem")
        if rule == "monochrome":
            hue = override["bias"]
            field, accent = (hue, 0.20, 0.10), (hue, 0.62, 0.14)
        elif rule == "preferred":
            red, green, blue = override["color"]
            hue, light, sat = colorsys.rgb_to_hls(red / 255.0, green / 255.0, blue / 255.0)
            field, accent = (hue, 0.18, 0.10), (hue, light, sat)
        elif accent is None:
            # a chromatic field with no bright accent: lift the field's own hue for the trim
            accent = (field[0], 0.56, min(0.62, field[2] * 1.15))
        rows.append(
            {
                "name": name,
                "slug": slug,
                "icon": icon,
                "side": side,
                "align": align,
                "rule": rule,
                "note": override.get("note", ""),
                "grey": grey,
                "field": field,
                "accent": accent,
                "tok": tokens_for(field, accent),
            }
        )
    return rows


def report(rows: list[dict]) -> None:
    """What each rule produced, and the contrast the palette holds against its own surface."""

    def rgb(value: str) -> tuple[int, int, int]:
        return tuple(int(value[i : i + 2], 16) for i in (1, 3, 5))  # type: ignore[return-value]

    header = f"{'faction':16} {'rule':10} {'plane':9} {'trim':9} {'ink':9} contrast on surface"
    print(header)
    for row in rows:
        tok = row["tok"]
        surface = rgb(tok["surface"])
        ratios = " / ".join(
            f"{contrast(rgb(tok[key]), surface):.1f}" for key in ("ink", "muted", "trim")
        )
        print(
            f"{plain(row['name']):16} {row['rule']:10} {tok['plane']:9} "
            f"{tok['trim']:9} {tok['ink']:9} {ratios}"
        )


def emit(rows: list[dict]) -> None:
    """The demo stylesheet, the emblems beside it, and one demo page per faction."""
    css = [
        """/* One skin per Edain faction, derived from the faction's own emblem in
   sage_mods/edain/icons/ by tools/build_faction_skins.py. Two anchors come out of the art -
   the dark field it is drawn on and the brightest accent drawn over it - and every other
   token is a fixed function of those two, so the palettes are sampled rather than chosen.

   Three emblems are monochrome and say nothing on their own: Isengard borrows the gold Edain
   set as its PreferredColor in playertemplate.ini, and Gondor and Arnor stay the silver they
   are drawn in, with a hue bias noted on the gallery page.

   The chart series, the faction stripes and the type stack are shared with the five
   directions in theme.css - they mean the same thing on every page, so they are not the
   faction's to recolour. Load this sheet after theme.css. */
"""
    ]
    for row in rows:
        tok = row["tok"]
        css.append(f"""/* {plain(row["name"])} - {row["side"]}, {row["align"]}. {row["rule"]} */
[data-skin="{row["slug"]}"] {{
  --plane: {tok["plane"]}; --surface: {tok["surface"]}; --raise: {tok["raise_"]};
  --ink: {tok["ink"]}; --ink-2: {tok["ink2"]}; --muted: {tok["muted"]};
  --hair: {tok["hair"]}; --hair-2: {tok["hair2"]};
  --trim: {tok["trim"]}; --trim-hi: {tok["trimhi"]};
  --mark: {tok["mark"]}; --link: {tok["link"]}; --good: {tok["good"]};
  --track: {tok["track"]}; --bevel: {tok["bevel"]};
  --sans: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  --display: "Palatino Linotype", "Book Antiqua", Palatino, Georgia, serif;
  --mono: ui-monospace, Consolas, monospace;
  --radius: 2px;
{SHARED}
}}
""")
    with open(
        os.path.join(DEMO, "assets", "factions.css"), "w", encoding="utf-8", newline="\n"
    ) as handle:
        handle.write("\n".join(css))

    # the emblems, next to the sheet that samples them
    icons_out = os.path.join(DEMO, "assets", "icons")
    os.makedirs(icons_out, exist_ok=True)
    for row in rows:
        shutil.copyfile(os.path.join(ICONS, row["icon"]), os.path.join(icons_out, row["icon"]))

    # one full page per faction, off the stone demo's markup
    with open(os.path.join(DEMO, "stone.html"), encoding="utf-8") as handle:
        base = handle.read()
    body = base[base.index('<div class="sheet">') : base.index("</body>")]
    foot = (
        "One component sheet, tokens per skin - <code>assets/theme.css</code>.",
        "One component sheet, palettes sampled per faction - <code>assets/factions.css</code>.",
    )
    assert foot[0] in body, "the demo footer moved; the faction pages would credit the wrong sheet"

    def nav(current: str) -> str:
        out = [
            '<nav class="switch">',
            "  <span>Faction</span>",
            '  <a href="factions.html">All 13 &amp; palettes</a>',
        ]
        for row in rows:
            mark = ' aria-current="page"' if row["slug"] == current else ""
            out.append(f'  <a href="faction-{row["slug"]}.html"{mark}>{row["name"]}</a>')
        out.append('  <a href="index.html">Directions</a>')
        out.append("</nav>")
        return "\n".join(out)

    for row in rows:
        page = f"""<!DOCTYPE html>
<html lang="en" data-skin="{row["slug"]}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{row["name"]} skin - Rohan corpus - theme spike</title>
<link rel="stylesheet" href="assets/theme.css">
<link rel="stylesheet" href="assets/factions.css">
</head>
<body data-skin="{row["slug"]}">
{nav(row["slug"])}
{body.replace(*foot)}</body>
</html>
"""
        with open(
            os.path.join(DEMO, f"faction-{row['slug']}.html"), "w", encoding="utf-8", newline="\n"
        ) as handle:
            handle.write(page)

    print(f"wrote assets/factions.css, assets/icons/, and {len(rows)} faction pages")


GALLERY_CSS = """
.fx-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); gap: 16px; }
.fx-card { border: 1px solid var(--hair); border-radius: 6px; overflow: hidden; background: var(--raise); display: flex; flex-direction: column; }
.fx-head { display: flex; align-items: center; gap: 12px; padding: 12px 14px; }
.fx-head img { width: 52px; height: 52px; flex: 0 0 auto; border-radius: 4px; background: #0c0c0c; }
.fx-name { display: flex; flex-direction: column; gap: 1px; min-width: 0; }
.fx-name h3 { margin: 0; font-size: 16px; letter-spacing: -0.01em; }
.fx-name em { font-size: 11.5px; font-style: normal; color: var(--ink-2); }
.fx-rule { margin-left: auto; font-family: var(--mono); font-size: 10px; letter-spacing: 0.03em; text-transform: uppercase; color: var(--ink-2); border: 1px solid var(--hair); border-radius: 3px; padding: 2px 6px; white-space: nowrap; }
.fx-sw { display: flex; padding: 0 14px 12px; gap: 4px; }
.fx-sw i { flex: 1 1 auto; height: 22px; border-radius: 3px; border: 1px solid rgba(128, 128, 128, 0.3); }
.fx-demo { padding: 14px; display: flex; flex-direction: column; gap: 10px; border-top: 1px solid var(--hair); background: var(--plane); color: var(--ink); font: 14px/1.55 var(--sans); }
.fx-demo table { font-size: 13px; }
.fx-demo .track { width: 52px; }
.fx-demo .pct { min-width: 30px; }
.fx-note { padding: 11px 14px 0; margin: 0; font-size: 12px; color: var(--ink-2); }
.fx-foot { display: flex; align-items: baseline; gap: 10px; padding: 11px 14px 12px; margin-top: auto; }
.fx-foot code { font-family: var(--mono); font-size: 11px; color: var(--ink-2); }
.fx-foot a { margin-left: auto; font-size: 13px; color: var(--mark); }
"""  # noqa: E501 - the gallery's own CSS, one rule per line

CARD = """    <div class="fx-card">
      <div class="fx-head">
        <img src="assets/icons/{icon}" alt="{plain} emblem" />
        <div class="fx-name"><h3>{name}</h3><em>{side} &middot; {align}</em></div>
        <span class="fx-rule">{rule}</span>
      </div>
      <div class="fx-sw">{swatches}</div>
      <div class="fx-demo" data-skin="{slug}">
        <div class="tiles">
          <div class="tile"><div class="k">Win rate</div><div class="v">54.2<small>%</small></div></div>
          <div class="tile"><div class="k">Replays</div><div class="v">412</div></div>
        </div>
        <div class="tablewrap"><table><tbody>
          <tr><td><span class="fac" style="--f: var(--trim)">{name}</span><span class="badge">Patched</span></td>
              <td><span class="bar"><span class="track"><i></i><span class="fill above" style="width: 9%"></span></span><span class="pct">59%</span></span></td></tr>
          <tr><td><span class="fac" style="--f: var(--muted)">Opponent</span></td>
              <td><span class="bar"><span class="track"><i></i><span class="fill below" style="width: 9%"></span></span><span class="pct">41%</span></span></td></tr>
        </tbody></table></div>
      </div>{note}
      <div class="fx-foot"><code>{trim}</code><a href="faction-{slug}.html">Full page &rarr;</a></div>
    </div>"""  # noqa: E501 - generated markup, not source to read at 100 columns

PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Edain faction skins - pySAGE HTML surfaces</title>
<link rel="stylesheet" href="assets/theme.css">
<link rel="stylesheet" href="assets/factions.css">
<link rel="stylesheet" href="assets/compare.css">
<style>{css}</style>
</head>
<body>
<div class="wrap">

  <header class="lede">
    <div class="eyebrow">pySAGE &middot; theme spike</div>
    <h1>Thirteen skins, one per Edain faction</h1>
    <p>The five directions are design choices. These are not: each palette is sampled from
    that faction&rsquo;s own emblem in <code>sage_mods/edain/icons/</code>. Two anchors come out
    of the art &mdash; the dark field it is drawn on, and the brightest accent drawn over it
    &mdash; and every other token is a fixed function of those two. Nothing here was picked by
    eye except where the rule ran out, and those three are labelled.</p>
    <p>Three emblems are monochrome. <strong>Isengard</strong> is the one case the mod answers
    on its own: Edain moved it off the stock team colour to a gold in
    <code>playertemplate.ini</code>, so that gold is the trim. <strong>Gondor</strong> and
    <strong>Arnor</strong> get nothing from either source &mdash; nearly every faction still
    shares the stock <code>PreferredColor = R:43 G:150 B:179</code> &mdash; so they stay the
    silver they are drawn in, with a hue bias that is the only judgement call in the set.</p>
    <p>The chart series, the faction stripes and the type stack stay shared with the five
    directions: they mean the same thing on every page, so they are not the faction&rsquo;s to
    recolour. Every trim clears 4.5:1 on its own surface &mdash; where a faction&rsquo;s accent
    came out darker than that, the rule lifts it and keeps the hue.</p>
  </header>

  <section class="block">
    <div class="fx-grid">
{cards}
    </div>
  </section>

  <footer class="close">
    <p><strong>Two things go wrong at thirteen that never came up at five.</strong></p>
    <ul>
      <li><strong>The diverging bar fights the trim.</strong> Cool is above the line and warm is
      below it on every skin, but Mordor, Iron Hills and Misty Mountains <em>are</em> that warm,
      and Lothl&oacute;rien is that cool. The rule rotates the colliding side away rather than
      letting a faction paint over the meaning; Mordor is where you can see how little headroom
      is left.</li>
      <li><strong>Sub-factions of one side land close together.</strong> Erebor and Ered Luin
      both sample to a gold trim, and Gondor, Arnor and Belfalas are three blues. That is the
      art being honest &mdash; they are meant to read as kin. If these ever became a picker, the
      emblem does the identifying, not the palette.</li>
    </ul>
    <p>Generated by <code>tools/build_faction_skins.py</code>: re-run it and every palette here
    moves with the art. The emblems are the source, this page is the output.</p>
  </footer>

</div>
</body>
</html>
"""


def gallery(rows: list[dict]) -> None:
    """The gallery page: every palette shown beside the emblem it was sampled from."""
    cards = []
    for row in rows:
        tok = row["tok"]
        swatches = "".join(
            f'<i style="background: {tok[key]}" title="{key}"></i>'
            for key in ("plane", "surface", "hair", "trim", "mark", "link")
        )
        note = f'\n      <p class="fx-note">{row["note"]}</p>' if row["note"] else ""
        cards.append(
            CARD.format(
                icon=row["icon"],
                plain=plain(row["name"]),
                name=row["name"],
                side=row["side"],
                align=row["align"],
                slug=row["slug"],
                trim=tok["trim"],
                rule=RULE_LABELS[row["rule"]],
                swatches=swatches,
                note=note,
            )
        )
    with open(os.path.join(DEMO, "factions.html"), "w", encoding="utf-8", newline="\n") as handle:
        handle.write(PAGE.format(css=GALLERY_CSS, cards="\n".join(cards)))
    print(f"wrote factions.html with {len(cards)} cards")


def _skin_entry(slug: str, name: str, tok: dict[str, str]) -> str:
    """One `SKINS` entry, tokens grouped onto shared lines so a palette reads as a palette.

    **The grouping is the information.** Ground, ink, hairlines and trim are each a set that is
    chosen together and read together, and one keyword per line - which is what `ruff format`
    would make of this - turns fourteen colours into fourteen unrelated lines and the table into
    240 of them. `FMT_OFF` is what buys the layout; without the fence the formatter unpacks every
    entry the moment anyone runs the generator.
    """
    return (
        f'    "{slug}": Skin(\n'
        f'        name="{name}",\n'
        f'        plane="{tok["plane"]}", surface="{tok["surface"]}", '
        f'raise_="{tok["raise_"]}",\n'
        f'        ink="{tok["ink"]}", ink_2="{tok["ink2"]}", muted="{tok["muted"]}",\n'
        f'        hair="{tok["hair"]}", hair_2="{tok["hair2"]}",\n'
        f'        trim="{tok["trim"]}", trim_hi="{tok["trimhi"]}",\n'
        f'        mark="{tok["mark"]}", link="{tok["link"]}", good="{tok["good"]}", '
        f'track="{tok["track"]}",\n'
        "    ),\n"
    )


def webtheme(rows: list[dict]) -> None:
    """Paste the palettes into `sage_utils/webtheme.py`, below its marker.

    That module is what the generated site imports, so this is what makes a re-run move the
    published pages' colours and not just the demo's.
    """
    out = [
        MARKER,
        FMT_OFF,
        "",
        "SKINS: dict[str, Skin] = {",
        _skin_entry("steel", "Steel & azure", STEEL),
    ]
    for row in rows:
        out.append(_skin_entry(row["slug"], plain(row["name"]), row["tok"]))
    out.append("}\n")
    out.append('STEEL = SKINS["steel"]\n')

    out.append("# Which emblem each palette was sampled from.")
    out.append("_EMBLEM_SKINS = {")
    for row in rows:
        out.append(f'    "{row["icon"]}": "{row["slug"]}",')
    out.append("}\n")

    # Every spelling a corpus might show for a faction: the mod's own aggregation labels (from
    # Edain's FACTION_ICONS, joined through the emblem) and each skin's display name.
    aliases = {plain(row["name"]): row["slug"] for row in rows}
    by_icon = {row["icon"]: row["slug"] for row in rows}
    for label, icon in FACTION_ICONS.items():
        if icon in by_icon:
            aliases[label] = by_icon[icon]
    out.append("# Aggregation labels and display names, normalised, to the skin they name.")
    out.append("_LABEL_SKINS = {")
    for label in sorted(aliases, key=lambda name: (aliases[name], name)):
        normalised = "".join(c for c in label.lower() if c.isalnum())
        out.append(f'    "{normalised}": "{aliases[label]}",  # {label}')
    out.append("}")
    out.append(FMT_ON)

    with open(WEBTHEME, encoding="utf-8") as handle:
        source = handle.read()
    assert MARKER in source, "webtheme.py lost its generated marker"
    with open(WEBTHEME, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(source[: source.index(MARKER)] + "\n".join(out) + "\n")
    print(f"wrote {os.path.relpath(WEBTHEME, REPO)} ({len(rows) + 1} skins)")


def main() -> None:
    rows = build()
    report(rows)
    emit(rows)
    gallery(rows)
    webtheme(rows)


if __name__ == "__main__":
    main()
