"""Tests for the upgrade-alias patch: the apply/verify/detect round trip on a synthetic image,
and an emulated run of the cave itself.

The cave is 102 bytes of hand-written x86 that scans a string, writes into it, calls two engine
helpers and returns for them. Nothing about that is checkable by looking at bytes: a wrong ModRM,
a comparison with the wrong polarity or a stack left four bytes off all produce a binary that
applies and verifies clean and then reads the wrong upgrade. So the second half of this file maps
the real generated bytes into Unicorn with stubs for the two callees and runs them, which is the
only way the register and stack discipline gets tested at all.
"""

from __future__ import annotations

import faulthandler
import struct

import pytest

from sage_ini.model.aliases import ALIAS_SEPARATOR
from sage_patch.addresses import (
    NAME_KEY_FROM_CSTR,
    THE_NAME_KEY_GENERATOR,
    UPGRADE_CENTER_FIND_UPGRADE,
    UPGRADE_CENTER_FIND_UPGRADE_BY_KEY,
    UPGRADE_CENTER_FIND_UPGRADE_RESUME,
)
from sage_patch.patches.upgrade_alias import (
    ANCHORS,
    HOOK_ORIGINAL,
    HOOK_VA,
    SECTION_NAME,
    SEPARATOR,
    UpgradeAliasPatch,
    build_code,
)
from sage_patch.utils import find_section, va_to_offset
from tests.sage_patch.synthetic import upgrade_alias_image


class TestPatchSites:
    def test_the_separator_matches_the_linter(self):
        # The engine and `sage_ini` must agree on the character, or the linter would accept
        # names this build rejects.
        assert chr(SEPARATOR) == ALIAS_SEPARATOR

    def test_the_hook_is_exactly_five_bytes(self):
        # A 5-byte jmp replaces `push esi` + `push [esp+8]` with nothing left over, so no NOP
        # padding is needed and the resume point is the very next byte.
        assert len(HOOK_ORIGINAL) == 5
        assert HOOK_VA + len(HOOK_ORIGINAL) == UPGRADE_CENTER_FIND_UPGRADE_RESUME

    def test_the_hook_site_is_the_upgrade_lookup(self):
        assert HOOK_VA == UPGRADE_CENTER_FIND_UPGRADE


class TestApply:
    def test_apply_then_verify_and_detect(self):
        image = upgrade_alias_image()
        patch = UpgradeAliasPatch()
        patch.apply(image)

        assert patch.verify(image) == []
        detected = UpgradeAliasPatch.detect(image)
        assert detected is not None
        assert detected.name == "upgrade-alias"

    def test_a_clean_image_is_not_detected(self):
        assert UpgradeAliasPatch.detect(upgrade_alias_image()) is None

    def test_the_hook_becomes_a_jump_to_the_cave(self):
        image = upgrade_alias_image()
        UpgradeAliasPatch().apply(image)

        located = find_section(image, SECTION_NAME)
        assert located is not None
        section_va = located[0]
        off = va_to_offset(image, HOOK_VA)
        assert image[off] == 0xE9
        assert HOOK_VA + 5 + struct.unpack_from("<i", image, off + 1)[0] == section_va

    def test_applying_twice_raises_rather_than_double_patching(self):
        image = upgrade_alias_image()
        UpgradeAliasPatch().apply(image)
        with pytest.raises(ValueError):
            UpgradeAliasPatch().apply(image)

    @pytest.mark.parametrize("va", sorted(ANCHORS))
    def test_a_moved_anchor_is_refused(self, va):
        # Every address the cave jumps to or calls is asserted, so a build whose layout moved
        # fails at apply time instead of hashing through the wrong helper.
        image = upgrade_alias_image()
        off = va_to_offset(image, va)
        image[off] ^= 0xFF
        with pytest.raises(ValueError, match=f"{va:#010x}"):
            UpgradeAliasPatch().apply(image)

    def test_a_moved_hook_site_is_refused(self):
        image = upgrade_alias_image()
        off = va_to_offset(image, HOOK_VA)
        image[off] ^= 0xFF
        with pytest.raises(ValueError):
            UpgradeAliasPatch().apply(image)


unicorn = pytest.importorskip("unicorn", reason="the emulator harness needs unicorn")

from unicorn import UC_ARCH_X86, UC_HOOK_CODE, UC_MODE_32, Uc  # noqa: E402
from unicorn.x86_const import (  # noqa: E402
    UC_X86_REG_EAX,
    UC_X86_REG_EBX,
    UC_X86_REG_ECX,
    UC_X86_REG_EDI,
    UC_X86_REG_ESI,
    UC_X86_REG_ESP,
)

#: Where the synthetic world lives. Far from the image, so a stray read faults instead of quietly
#: finding something.
_HEAP = 0x20000000
_STACK = 0x30000000
_DONE = 0x40000000  # the return address pushed for the cave; reaching it ends the run
_CAVE = 0x00AD3000
_PAGE = 0x1000

_CENTER = 0x11110000  # the `UpgradeCenter *` handed to the call in `ecx`
_GENERATOR = 0x22220000  # what `THE_NAME_KEY_GENERATOR` holds
_KEY = 0x33330000  # what the `nameToKey` stub returns
_TEMPLATE = 0x44440000  # what the `findUpgradeByKey` stub returns
_STOCK = 0x55550000  # what the stock-path stub returns, i.e. "no alias, unchanged behaviour"

#: `ebx`, `esi` and `edi` are callee-saved here, so the cave must give them back untouched.
_SAVED = {UC_X86_REG_EBX: 0xBBBBBBBB, UC_X86_REG_ESI: 0x51515151, UC_X86_REG_EDI: 0xD1D1D1D1}


class _Run:
    """One emulated call into the cave, with the two engine helpers stubbed."""

    def __init__(self, name: bytes | None):
        self.calls: list[tuple[str, object]] = []
        self.uc = uc = Uc(UC_ARCH_X86, UC_MODE_32)
        # `UPGRADE_CENTER_FIND_UPGRADE_RESUME` shares `findUpgradeByKey`'s page and is not mapped
        # separately; every other site is a page of its own.
        # `mem_map` raises and catches an SEH access violation inside Unicorn 2.1.4 on Windows -
        # every map still succeeds, but Python's fault handler prints a stack for each one, which
        # would bury the test output. Silenced around the mapping only.
        was_enabled = faulthandler.is_enabled()
        faulthandler.disable()
        try:
            for base in (
                _CAVE,
                _HEAP,
                _STACK,
                _DONE,
                NAME_KEY_FROM_CSTR & ~0xFFF,
                UPGRADE_CENTER_FIND_UPGRADE_BY_KEY & ~0xFFF,
                THE_NAME_KEY_GENERATOR & ~0xFFF,
            ):
                uc.mem_map(base, _PAGE)
        finally:
            if was_enabled:
                faulthandler.enable()

        uc.mem_write(_CAVE, build_code(_CAVE))
        uc.mem_write(THE_NAME_KEY_GENERATOR, struct.pack("<I", _GENERATOR))
        # `mov eax, <sentinel>` / `ret 4` - each stub returns its marker and cleans its one
        # argument, exactly as the real `__thiscall` helpers do.
        uc.mem_write(NAME_KEY_FROM_CSTR, b"\xb8" + struct.pack("<I", _KEY) + b"\xc2\x04\x00")
        uc.mem_write(
            UPGRADE_CENTER_FIND_UPGRADE_BY_KEY,
            b"\xb8" + struct.pack("<I", _TEMPLATE) + b"\xc2\x04\x00",
        )
        # The stock path arrives having pushed the argument and saved `esi`, so the stand-in
        # unwinds both before returning - the same shape the real body ends with.
        uc.mem_write(
            UPGRADE_CENTER_FIND_UPGRADE_RESUME,
            b"\x83\xc4\x04\x5e\xb8" + struct.pack("<I", _STOCK) + b"\xc2\x04\x00",
        )

        # The `AsciiString`: a pointer at +0 to a refcounted buffer whose chars start at +8.
        self.buffer = _HEAP + 0x100
        self.chars = self.buffer + 8
        if name is None:
            uc.mem_write(_HEAP, struct.pack("<I", 0))  # the engine's empty string
        else:
            uc.mem_write(_HEAP, struct.pack("<I", self.buffer))
            uc.mem_write(self.chars, name + b"\x00")
        self.name = name

        uc.hook_add(UC_HOOK_CODE, self._observe, begin=NAME_KEY_FROM_CSTR, end=NAME_KEY_FROM_CSTR)
        uc.hook_add(
            UC_HOOK_CODE,
            self._observe,
            begin=UPGRADE_CENTER_FIND_UPGRADE_BY_KEY,
            end=UPGRADE_CENTER_FIND_UPGRADE_BY_KEY,
        )

        self.esp0 = _STACK + 0x800
        uc.mem_write(self.esp0, struct.pack("<II", _DONE, _HEAP))  # return address, then the arg
        uc.reg_write(UC_X86_REG_ESP, self.esp0)
        uc.reg_write(UC_X86_REG_ECX, _CENTER)
        for register, value in _SAVED.items():
            uc.reg_write(register, value)
        uc.emu_start(_CAVE, _DONE)

    def _observe(self, uc, address, size, data):
        esp = uc.reg_read(UC_X86_REG_ESP)
        argument = struct.unpack("<I", uc.mem_read(esp + 4, 4))[0]
        this = uc.reg_read(UC_X86_REG_ECX)
        if address == NAME_KEY_FROM_CSTR:
            self.calls.append(("nameToKey", self._cstring(argument), this))
        else:
            self.calls.append(("findUpgradeByKey", argument, this))

    def _cstring(self, address: int) -> bytes:
        out = bytearray()
        while (byte := self.uc.mem_read(address + len(out), 1)[0]) != 0:
            out.append(byte)
        return bytes(out)

    @property
    def result(self) -> int:
        return self.uc.reg_read(UC_X86_REG_EAX)

    @property
    def hashed(self) -> bytes | None:
        """The name handed to `nameToKey`, or None when the stock path ran."""
        return next((c[1] for c in self.calls if c[0] == "nameToKey"), None)

    @property
    def buffer_now(self) -> bytes:
        return bytes(self.uc.mem_read(self.chars, len(self.name or b"") + 1))


class TestCaveExecution:
    def test_an_aliased_name_hashes_only_the_part_before_the_separator(self):
        run = _Run(b"Upgrade_TestBuilding@SmithyLevel2")
        assert run.hashed == b"Upgrade_TestBuilding"
        assert run.result == _TEMPLATE

    def test_the_key_it_hashed_is_the_key_it_looks_up(self):
        run = _Run(b"Upgrade_TestBuilding@SmithyLevel2")
        assert ("findUpgradeByKey", _KEY, _CENTER) in run.calls

    def test_both_helpers_get_the_right_this_pointer(self):
        run = _Run(b"Upgrade_TestBuilding@SmithyLevel2")
        assert ("nameToKey", b"Upgrade_TestBuilding", _GENERATOR) in run.calls
        assert ("findUpgradeByKey", _KEY, _CENTER) in run.calls

    def test_the_separator_is_put_back_before_returning(self):
        # The cave truncates the caller's own buffer in place; leaving the NUL there would
        # silently shorten a string the caller still owns.
        name = b"Upgrade_TestBuilding@SmithyLevel2"
        run = _Run(name)
        assert run.buffer_now == name + b"\x00"

    def test_two_aliases_of_one_upgrade_hash_the_same_name(self):
        # The whole point: different intents, one upgrade bit.
        first = _Run(b"Upgrade_TestBuilding@SmithyLevel2")
        second = _Run(b"Upgrade_TestBuilding@GateOpen")
        assert first.hashed == second.hashed == b"Upgrade_TestBuilding"

    def test_only_the_first_separator_splits(self):
        run = _Run(b"Upgrade_TestBuilding@A@B")
        assert run.hashed == b"Upgrade_TestBuilding"

    def test_a_trailing_separator_still_truncates(self):
        run = _Run(b"Upgrade_TestBuilding@")
        assert run.hashed == b"Upgrade_TestBuilding"

    @pytest.mark.parametrize(
        "name",
        [
            b"Upgrade_TestBuilding",  # the ordinary case, and 5368 of them in the base game
            b"@Upgrade_NoHelmet",  # the create-a-hero default-bling marker
            b"@",  # a lone marker
            b"",  # an empty name
            None,  # the engine's empty `AsciiString`, whose buffer pointer is NULL
        ],
    )
    def test_names_without_an_interior_separator_take_the_stock_path(self, name):
        run = _Run(name)
        assert run.result == _STOCK
        assert run.calls == []

    @pytest.mark.parametrize("name", [b"Upgrade_TestBuilding@SmithyLevel2", b"Upgrade_X"])
    def test_the_stack_is_balanced_like_a_ret_4(self, name):
        # Both paths must end `ret 4`: the return address plus the one argument.
        run = _Run(name)
        assert run.uc.reg_read(UC_X86_REG_ESP) == run.esp0 + 8

    @pytest.mark.parametrize("name", [b"Upgrade_TestBuilding@SmithyLevel2", b"Upgrade_X"])
    @pytest.mark.parametrize("register", sorted(_SAVED))
    def test_callee_saved_registers_survive(self, name, register):
        run = _Run(name)
        assert run.uc.reg_read(register) == _SAVED[register]
